#!/usr/bin/env python3
"""Generates lib/l10n/app_fa.arb and app_en.arb from one table so both languages
always have identical keys. Run: python3 tool/gen_arb.py
Placeholders written as {name} are typed as String (pre-format numbers/dates
in Dart). Keys starting with '_select_' are hand-written ICU."""
import json, re, os

T = {}
def k(key, fa, en, desc=None):
    T[key] = (fa, en, desc)

# ---------------------------------------------------------------- general
k('appName', 'بعداً', 'Later')
k('tagline', 'الان لازم نیست؛ فقط فراموشش نکن.', "Not now — just don't forget it.")
k('ok', 'باشه', 'OK')
k('cancel', 'انصراف', 'Cancel')
k('save', 'ذخیره', 'Save')
k('delete', 'حذف', 'Delete')
k('edit', 'ویرایش', 'Edit')
k('close', 'بستن', 'Close')
k('retry', 'تلاش دوباره', 'Try again')
k('done', 'انجام شد', 'Done')
k('next', 'بعدی', 'Next')
k('skip', 'رد کردن', 'Skip')
k('continueLabel', 'ادامه', 'Continue')
k('undo', 'برگردان', 'Undo')
k('add', 'اضافه کن', 'Add')
k('search', 'جستجو', 'Search')
k('all', 'همه', 'All')
k('none', 'هیچ‌کدام', 'None')
k('proBadge', 'Pro', 'Pro')
k('loading', 'در حال بارگذاری…', 'Loading…')
k('errorGeneric', 'یه مشکلی پیش اومد. دوباره تلاش کن.', 'Something went wrong. Please try again.')
k('errorLoad', 'بارگذاری اطلاعات ناموفق بود.', "Couldn't load your data.")
k('navHome', 'خانه', 'Home')
k('navList', 'بعداً', 'Later')
k('navHistory', 'تاریخچه', 'History')
k('navSettings', 'تنظیمات', 'Settings')
k('semAdd', 'افزودن مورد جدید', 'Add a new item')

# ------------------------------------------------------------- onboarding
k('onb1Title', 'الان لازم نیست.', "You don't need it now.")
k('onb1Body', 'ذهنت را از هزارتا کار نیمه‌کاره خالی کن.', 'Free your mind from a thousand half-finished things.')
k('onb2Title', 'هر چی نمی‌خوای یادت بره، اینجا بذارش.', "Keep anything you don't want to forget, right here.")
k('onb2Body', 'مقاله، فیلم، خرید، ایده، لینک، یه تماس… فقط بنویس یا از هر برنامه‌ای «اشتراک‌گذاری» کن.', 'An article, a movie, a purchase, an idea, a link, a call… just type it or Share it from any app.')
k('onb3Title', 'بعداً خودش به تو یادآوری می‌کند.', 'Later reminds you by itself.')
k('onb3Body', 'یه تاریخ و ساعت بده؛ یا نده و هر وقت وقت آزاد داشتی بگو «یه مورد بهم بده».', 'Give it a date and time — or don\'t, and ask "give me one" whenever you have a moment.')
k('onb4Title', 'بدون حساب کاربری، بدون سرور.', 'No account, no server.')
k('onb4Body', 'اطلاعاتت فقط روی دستگاه خودت می‌ماند و حتی بدون اینترنت کار می‌کند.', 'Your data stays on your own device and works even without internet.')
k('onb5Title', 'آماده‌ای؟', 'Ready?')
k('onb5Body', 'هر چیزی که الان وقتش نیست را همین‌جا بگذار.', "Put anything that isn't for now right here.")
k('onbStart', 'بزن بریم', "Let's go")

# --------------------------------------------------------------- legal
k('legalTitle', 'قبل از شروع', 'Before you start')
k('legalIntro', 'لطفاً قوانین استفاده و سیاست حریم خصوصی را بخوان و تأیید کن.', 'Please read and accept the Terms of Use and the Privacy Policy.')
k('termsTitle', 'قوانین استفاده', 'Terms of Use')
k('privacyTitle', 'سیاست حریم خصوصی', 'Privacy Policy')
k('legalAccept', 'قوانین استفاده و سیاست حریم خصوصی را خوانده‌ام و می‌پذیرم.', 'I have read and accept the Terms of Use and Privacy Policy.')
k('legalContinue', 'تأیید و ورود', 'Accept and continue')
k('legalLoadError', 'بارگذاری متن ناموفق بود.', "Couldn't load the text.")
k('legalUpdatedTitle', 'به‌روزرسانی قوانین', 'Updated terms')

# ------------------------------------------------------------------ home
k('homeWaiting', '{count} مورد منتظر توست', '{count} items are waiting for you')
k('homeWaitingOne', 'یک مورد منتظر توست', 'One item is waiting for you')
k('homeEmptyTitle', 'هنوز چیزی برای بعداً نداری.', 'Nothing for later yet.')
k('homeEmptyBody', 'چه خوب. فعلاً ذهنت آزاده. 🌱', 'Nice. Your mind is free for now. 🌱')
k('homeEmptyCta', 'اولین مورد را اضافه کن', 'Add your first item')
k('statToday', 'امروز', 'Today')
k('statWeek', 'این هفته', 'This week')
k('statNoDate', 'بدون تاریخ', 'No date')
k('statOverdue', 'عقب‌افتاده', 'Overdue')
k('statStale', 'مانده‌ها', 'Waiting long')
k('pickCardTitle', '🎯 یه مورد بهم بده', '🎯 Give me one')
k('pickCardSub', 'نمی‌دونی الان چی کار کنی؟ من انتخاب می‌کنم.', "Don't know what to do now? I'll choose.")
k('timeCardTitle', 'الان چقدر وقت داری؟', 'How much time do you have?')
k('minutesN', '{n} دقیقه', '{n} min')
k('hourOne', '۱ ساعت', '1 hour')
k('anyTime', 'مهم نیست', "Doesn't matter")
k('homeTodaySection', 'امروز و عقب‌افتاده‌ها', 'Today & overdue')
k('homeSeeAll', 'همه', 'See all')
k('staleBannerTitle', '{count} مورد مدت‌هاست منتظرند', '{count} items have been waiting a long time')
k('staleBannerBody', 'یه نگاه سریع بنداز؛ نگه دار یا رها کن.', 'Take a quick look: keep or let go.')

# ------------------------------------------------------ decide / smart pick
k('decideTitle', 'تصمیم نگیر', "Don't decide")
k('decideIntro', 'نمی‌دونم الان چی کار کنم.', "I don't know what to do right now.")
k('decideLabel', '🎯 پیشنهاد بعدی تو:', '🎯 Your next suggestion:')
k('decideAbout', 'حدود {n} دقیقه', 'About {n} min')
k('decideDo', 'انجامش می‌دم', "I'll do it")
k('decideLater', 'بعداً', 'Later')
k('decideAnother', 'مورد دیگری بده', 'Give me another')
k('decideNone', 'چیزی برای پیشنهاد ندارم', 'Nothing to suggest')
k('decideNoneBody', 'لیستت خالیه یا چیزی به این زمان نمی‌خوره. 🌱', 'Your list is empty or nothing fits. 🌱')
k('decideNoMore', 'مورد دیگری نمانده.', 'No more items to suggest.')
k('decideDoneToast', 'آفرین! انجام شد ✓', 'Nice! Done ✓')
k('smartPickTitle', 'پیشنهاد هوشمند', 'Smart pick')
k('smartPickHeader', 'الان چقدر وقت داری؟', 'How much time do you have now?')
k('smartPickResultsFor', 'مناسب {time}', 'Fits {time}')
k('smartPickResultsAny', 'پیشنهادها', 'Suggestions')
k('smartPickEmpty', 'برای این مدت چیزی پیدا نکردم.', "I couldn't find anything for that long.")
k('smartPickProHint', 'پیشنهاد پیشرفته (اولویت و فیلتر دسته) با Pro', 'Advanced picks (priority & category filter) with Pro')
k('smartPickCategory', 'فقط از دسته‌ی…', 'Only from category…')
k('smartPickAllCategories', 'همه‌ی دسته‌ها', 'All categories')

# ------------------------------------------------------------------ list
k('listTitle', 'بعداً', 'Later')
k('searchHint', 'جستجو در بعداً…', 'Search Later…')
k('searchAdvancedHint', 'جستجوی پیشرفته (برچسب، لینک، یادداشت) با Pro', 'Advanced search (tags, links, notes) with Pro')
k('filterAll', 'همه', 'All')
k('filterToday', 'امروز', 'Today')
k('filterWeek', 'این هفته', 'This week')
k('filterNoDate', 'بدون تاریخ', 'No date')
k('filterOverdue', 'عقب‌افتاده', 'Overdue')
k('filterHigh', 'اولویت بالا', 'High priority')
k('filterStale', 'مانده‌ها', 'Waiting long')
k('sortTitle', 'مرتب‌سازی', 'Sort')
k('sortNewest', 'جدیدترین', 'Newest')
k('sortOldest', 'قدیمی‌ترین', 'Oldest')
k('sortDeadline', 'نزدیک‌ترین موعد', 'Nearest deadline')
k('sortPriority', 'اولویت', 'Priority')
k('sortShortest', 'کوتاه‌ترین کار', 'Shortest task')
k('sortLongest', 'طولانی‌ترین کار', 'Longest task')
k('listEmptyFiltered', 'چیزی پیدا نشد', 'Nothing found')
k('listEmptyFilteredBody', 'فیلتر یا عبارت جستجو را عوض کن.', 'Try changing the filter or search.')
k('smartFiltersPro', 'فیلترهای هوشمند با Pro', 'Smart filters with Pro')

# ------------------------------------------------------------ item / cards
k('overdue', 'عقب‌افتاده', 'Overdue')
k('waitingDays', '{n} روز است منتظر', 'Waiting {n} days')
k('dueToday', 'امروز', 'Today')
k('dueTomorrow', 'فردا', 'Tomorrow')
k('atTime', 'ساعت {time}', 'at {time}')
k('noDate', 'بدون تاریخ', 'No date')
k('priorityHigh', 'اولویت بالا', 'High priority')
k('priorityNormal', 'عادی', 'Normal')
k('priorityLow', 'کم', 'Low')
k('priority', 'اولویت', 'Priority')
k('duration', 'زمان تخمینی', 'Estimated time')
k('minutesShort', '{n} د', '{n}m')
k('reminder', 'یادآوری', 'Reminder')
k('repeat', 'تکرار', 'Repeat')
k('repeatNone', 'یک‌بار', 'Once')
k('repeatDaily', 'هر روز', 'Every day')
k('repeatWeekly', 'هر هفته', 'Every week')
k('repeatMonthly', 'هر ماه', 'Every month')
k('snoozedTimes', '{n} بار به بعد رفته', 'Snoozed {n} times')
k('itemDone', 'انجام شد', 'Done')
k('itemSnooze', 'بعداً', 'Later')
k('itemDrop', 'بی‌خیالش شدم', 'Let it go')
k('itemOpenLink', 'باز کردن لینک', 'Open link')
k('itemLinkFailed', 'لینک باز نشد.', "Couldn't open the link.")
k('toastDone', 'انجام شد ✓', 'Done ✓')
k('toastDropped', 'کنار گذاشته شد', 'Set aside')
k('toastDeleted', 'حذف شد', 'Deleted')
k('toastSnoozed', 'منتقل شد به {when}', 'Moved to {when}')
k('toastSaved', 'ذخیره شد', 'Saved')
k('toastAdded', 'به بعداً اضافه شد', 'Added to Later')
k('toastReopened', 'به لیست برگشت', 'Back in your list')
k('confirmDeleteTitle', 'حذف این مورد؟', 'Delete this item?')
k('confirmDeleteBody', 'این مورد برای همیشه پاک می‌شود.', 'This item will be permanently deleted.')
k('createdOn', 'ثبت‌شده در {date}', 'Added on {date}')
k('itemNotFound', 'این مورد دیگر وجود ندارد.', 'This item no longer exists.')

# --------------------------------------------------------------- add / edit
k('addTitle', 'چیزی برای بعداً', 'Something for later')
k('editTitle', 'ویرایش', 'Edit')
k('titleHint', 'چی رو بذارم برای بعداً؟', 'What should I keep for later?')
k('titleRequired', 'یه عنوان بنویس', 'Write a title')
k('moreOptions', 'گزینه‌های بیشتر', 'More options')
k('lessOptions', 'کمتر', 'Fewer options')
k('fieldDescription', 'توضیح', 'Description')
k('fieldNote', 'یادداشت', 'Note')
k('fieldUrl', 'لینک', 'Link')
k('urlInvalid', 'لینک معتبر نیست (فقط http و https).', 'Invalid link (http and https only).')
k('fieldTags', 'برچسب‌ها', 'Tags')
k('fieldTagsHint', 'با کاما جدا کن', 'Separate with commas')
k('fieldCategory', 'دسته', 'Category')
k('fieldDate', 'تاریخ', 'Date')
k('fieldTime', 'ساعت', 'Time')
k('datePick', 'انتخاب تاریخ…', 'Pick a date…')
k('timePick', 'انتخاب ساعت…', 'Pick a time…')
k('timeNone', 'بدون ساعت', 'No time')
k('reminderOff', 'بدون یادآوری', 'No reminder')
k('reminderAtTime', 'سر وقت', 'At the time')
k('reminderBefore10', '۱۰ دقیقه قبل', '10 min before')
k('reminderBefore60Label', '۱ ساعت قبل', '1 hour before')
k('reminderBefore1d', '۱ روز قبل', '1 day before')
k('reminderNeedsDate', 'برای یادآوری یه تاریخ لازمه.', 'A reminder needs a date.')
k('reminderAtDefault', 'ساعت {time} (پیش‌فرض)', 'at {time} (default)')
k('repeatProHint', 'یادآوری تکرارشونده با Pro', 'Repeating reminders with Pro')
k('durationUnknown', 'نامشخص', 'Unknown')
k('durationCustom', 'دلخواه', 'Custom')
k('durationCustomHint', 'چند دقیقه؟', 'How many minutes?')
k('quickToday', 'امروز', 'Today')
k('quickTomorrow', 'فردا', 'Tomorrow')
k('quickWeekend', 'آخر هفته', 'Weekend')
k('quickNextWeek', 'هفته بعد', 'Next week')
k('quickNoDate', 'بدون تاریخ', 'No date')
k('quickCustom', 'تاریخ دیگر', 'Other date')
k('discardTitle', 'تغییرات ذخیره نشود؟', 'Discard changes?')
k('discardBody', 'چیزی که نوشته‌ای ذخیره نشده.', "What you typed hasn't been saved.")
k('discard', 'دور بینداز', 'Discard')

# ----------------------------------------------------------------- snooze
k('snoozeTitle', 'به کِی موکولش کنم؟', 'Snooze until…')
k('snoozeTonight', 'امشب', 'Tonight')
k('snoozeTomorrow', 'فردا', 'Tomorrow')
k('snoozeWeekend', 'آخر هفته', 'This weekend')
k('snoozeNextWeek', 'هفته بعد', 'Next week')
k('snoozeNextMonth', 'ماه بعد', 'Next month')
k('snoozeCustom', 'تاریخ دلخواه', 'Pick a date')
k('snoozeNoDate', 'بدون تاریخ', 'No date')
k('datePickerTitle', 'انتخاب تاریخ', 'Pick a date')
k('prevMonth', 'ماه قبل', 'Previous month')
k('nextMonth', 'ماه بعد', 'Next month')
k('today', 'امروز', 'Today')
k('clear', 'پاک کردن', 'Clear')

# ------------------------------------------------------------ stale review
k('staleTitle', 'بعداً، نه هیچ‌وقت', 'Later, not never')
k('staleQuestion', 'این مورد {days} روز است منتظر توست.\nهنوز می‌خواهی نگهش داری؟', 'This has been waiting for you for {days} days.\nDo you still want to keep it?')
k('staleKeep', 'نگه دار', 'Keep')
k('staleSnooze', 'برای بعداً تنظیم کن', 'Schedule for later')
k('staleDone', 'انجام شد', 'Done')
k('staleDrop', 'بی‌خیالش شدم', 'Let it go')
k('staleProgress', '{i} از {n}', '{i} of {n}')
k('staleAllDone', 'همه‌چی مرتبه ✨', 'All clear ✨')
k('staleAllDoneBody', 'لیستت سبک‌تر شد.', 'Your list just got lighter.')
k('staleNoPressure', 'بدون عجله؛ هیچ تصمیمی اشتباه نیست.', 'No rush; no decision is wrong.')

# ------------------------------------------------------- history / stats
k('historyTitle', 'تاریخچه', 'History')
k('periodToday', 'امروز', 'Today')
k('periodWeek', 'این هفته', 'This week')
k('periodMonth', 'این ماه', 'This month')
k('periodAll', 'همه', 'All')
k('historyEmpty', 'هنوز چیزی در تاریخچه نیست', 'Nothing in your history yet')
k('historyEmptyBody', 'کارهای انجام‌شده و کنار گذاشته‌شده اینجا می‌مانند.', 'Completed and set-aside items stay here.')
k('historyDoneAt', 'انجام شد · {date}', 'Done · {date}')
k('historyDroppedAt', 'کنار گذاشته شد · {date}', 'Set aside · {date}')
k('historyRestore', 'برگردان به لیست', 'Move back to list')
k('historyProNote', 'تاریخچه‌ی کامل (ماه و همه) با Pro', 'Full history (month & all) with Pro')
k('historyDisabled', 'ثبت تاریخچه خاموش است؛ فقط آمار ناشناس نگه داشته می‌شود.', 'History is off; only anonymous statistics are kept.')
k('statsTitle', 'آمار', 'Statistics')
k('statsDone', 'انجام‌شده', 'Completed')
k('statsDropped', 'کنار گذاشته‌شده', 'Set aside')
k('statsDeleted', 'حذف‌شده', 'Deleted')
k('statsSnoozed', 'بار به تعویق افتاده', 'Times snoozed')
k('statsActive', 'فعال', 'Active')
k('statsAvgWait', 'میانگین ماندن تا انجام', 'Average wait until done')
k('statsDaysValue', '{n} روز', '{n} days')
k('statsTopCategory', 'محبوب‌ترین دسته', 'Top category')
k('statsThisWeek', 'انجام‌شده در این هفته', 'Completed this week')
k('statsProLocked', 'آمار کامل با Pro', 'Full statistics with Pro')
k('statsNoData', '—', '—')

# ---------------------------------------------------------------- settings
k('settingsTitle', 'تنظیمات', 'Settings')
k('secAppearance', 'ظاهر', 'Appearance')
k('theme', 'تم', 'Theme')
k('themeLight', 'روشن', 'Light')
k('themeDark', 'تیره', 'Dark')
k('themeSystem', 'پیش‌فرض سیستم', 'System default')
k('accent', 'رنگ اصلی', 'Accent colour')
k('accentIndigo', 'بنفش', 'Indigo')
k('accentTeal', 'فیروزه‌ای', 'Teal')
k('accentRose', 'رُز', 'Rose')
k('accentAmber', 'کهربایی', 'Amber')
k('accentSlate', 'خاکستری', 'Slate')
k('appIcon', 'آیکون برنامه', 'App icon')
k('iconClassic', 'کلاسیک', 'Classic')
k('iconTeal', 'فیروزه‌ای', 'Teal')
k('iconRose', 'رُز', 'Rose')
k('iconDark', 'تیره', 'Dark')
k('iconChangeNote', 'با تغییر آیکون ممکن است چند لحظه‌ی دیگر در لانچر عوض شود.', 'The launcher may take a moment to refresh the icon.')
k('secReminders', 'یادآوری', 'Reminders')
k('remindersToggle', 'یادآوری‌ها', 'Reminders')
k('defaultReminderTime', 'ساعت پیش‌فرض یادآوری', 'Default reminder time')
k('privateNotifications', 'پنهان کردن متن در اعلان', 'Hide text in notifications')
k('privateNotificationsSub', 'عنوان موردها روی صفحه‌ی قفل دیده نشود.', "Item titles won't show on the lock screen.")
k('notifPermission', 'دسترسی اعلان', 'Notification access')
k('notifPermissionOn', 'فعال است', 'Enabled')
k('notifPermissionOff', 'غیرفعال است؛ برای باز کردن تنظیمات بزن', 'Disabled — tap to open settings')
k('exactAlarm', 'دقت یادآوری', 'Reminder accuracy')
k('exactAlarmOk', 'دقیق', 'Exact')
k('exactAlarmOff', 'تقریبی؛ «هشدار دقیق» مجاز نشده', 'Approximate — "exact alarms" not allowed')
k('batteryOptimization', 'محدودیت باتری', 'Battery restrictions')
k('batteryOptimizationSub', 'بعضی گوشی‌ها یادآوری را می‌بندند؛ بزن تا تنظیمات باز شود.', 'Some phones block reminders; tap to open the settings.')
k('sendTestNotification', 'ارسال اعلان آزمایشی', 'Send a test notification')
k('testNotificationSent', 'اعلان آزمایشی ارسال شد.', 'Test notification sent.')
k('secGeneral', 'عمومی', 'General')
k('language', 'زبان', 'Language')
k('langFa', 'فارسی', 'فارسی (Persian)')
k('langEn', 'English', 'English')
k('calendar', 'تقویم', 'Calendar')
k('calJalali', 'شمسی', 'Jalali (Persian)')
k('calGregorian', 'میلادی', 'Gregorian')
k('weekStart', 'شروع هفته', 'Start of week')
k('weekendDay', 'روز آخر هفته', 'Weekend day')
k('keepHistory', 'نگه داشتن تاریخچه', 'Keep history')
k('keepHistorySub', 'موردهای انجام‌شده و کنار گذاشته‌شده در آرشیو بمانند.', 'Keep completed and set-aside items in the archive.')
k('staleAfter', 'مرور مانده‌ها بعد از', 'Review long-waiting items after')
k('daysN', '{n} روز', '{n} days')
k('secData', 'اطلاعات', 'Data')
k('backupRestore', 'پشتیبان‌گیری و بازیابی', 'Backup & restore')
k('categoriesManage', 'مدیریت دسته‌ها', 'Manage categories')
k('secAbout', 'درباره', 'About')
k('proSettingsTitle', 'بعداً Pro', 'Later Pro')
k('proSettingsFree', 'نسخه‌ی رایگان', 'Free plan')
k('proSettingsActive', 'فعال تا {date}', 'Active until {date}')
k('about', 'درباره‌ی برنامه', 'About')
k('aboutBody', 'بعداً یک برنامه‌ی کوچک و سریع برای نگه‌داشتن چیزهایی است که الان وقتشان نیست؛ بدون حساب کاربری و بدون سرور.', "Later is a small, fast app for keeping things that aren't for now — no account, no server.")
k('aboutOffline', 'همه‌ی اطلاعات فقط روی دستگاه تو ذخیره می‌شود.', 'All your data is stored only on your device.')
k('aboutLicenses', 'مجوزهای متن‌باز', 'Open-source licences')
k('aboutContact', 'پشتیبانی', 'Support')
k('version', 'نسخه', 'Version')
k('versionValue', 'نسخه {v}', 'Version {v}')
k('resetApp', 'پاک کردن همه‌ی اطلاعات', 'Reset app')
k('resetAppSub', 'همه‌ی موردها، دسته‌ها، تاریخچه و تنظیمات', 'All items, categories, history and settings')
k('resetConfirmTitle', 'همه‌چیز پاک شود؟', 'Erase everything?')
k('resetConfirmBody', 'همه‌ی موردها، دسته‌ها، تاریخچه و تنظیمات این برنامه برای همیشه پاک می‌شود. این کار قابل بازگشت نیست.\n(اشتراک Pro از بین نمی‌رود.)\nپیشنهاد می‌کنیم اول پشتیبان بگیری.', 'All items, categories, history and settings will be permanently deleted. This cannot be undone.\n(Your Pro subscription is not affected.)\nWe suggest making a backup first.')
k('resetTypeHint', 'برای تأیید، کلمه‌ی «{word}» را بنویس', 'To confirm, type "{word}"')
k('resetWord', 'پاک', 'ERASE')
k('resetAction', 'پاک کردن همه‌چیز', 'Erase everything')
k('resetDone', 'همه‌چیز پاک شد.', 'Everything was erased.')

# ------------------------------------------------------------- categories
k('_select_categoryName', '{id, select, work{کار} read{خواندنی} watch{دیدنی} buy{خرید} idea{ایده} link{لینک} people{افراد} other{سایر}}', '{id, select, work{Work} read{To read} watch{To watch} buy{To buy} idea{Ideas} link{Links} people{People} other{Other}}')
k('categoryNew', 'دسته‌ی جدید', 'New category')
k('categoryEdit', 'ویرایش دسته', 'Edit category')
k('categoryNameHint', 'نام دسته', 'Category name')
k('categoryEmojiHint', 'ایموجی', 'Emoji')
k('categoryLimit', 'در نسخه‌ی رایگان تا {free} دسته‌ی سفارشی می‌توانی بسازی؛ Pro تا {pro} دسته.', 'The free plan allows {free} custom categories; Pro allows up to {pro}.')
k('categoryDeleteTitle', 'این دسته حذف شود؟', 'Delete this category?')
k('categoryDeleteBody', 'موردهای این دسته به «سایر» منتقل می‌شوند.', 'Its items will move to "Other".')
k('categoryBuiltin', 'دسته‌ی پیش‌فرض', 'Built-in category')

# ------------------------------------------------------- backup / restore
k('backupTitle', 'پشتیبان‌گیری و بازیابی', 'Backup & restore')
k('backupIntro', 'اطلاعات فقط روی همین دستگاه است. برای جابه‌جایی یا نصب مجدد، از آن‌ها فایل پشتیبان بگیر.', 'Your data lives only on this device. Make a backup file before moving or reinstalling.')
k('backupExport', 'خروجی گرفتن از اطلاعات', 'Export my data')
k('backupExportSub', 'یک فایل ‎.later‎ با همه‌ی موردها، دسته‌ها، تاریخچه و تنظیمات', 'A .later file with all items, categories, history and settings')
k('backupImport', 'بازیابی از فایل', 'Restore from file')
k('backupImportSub', 'فایل پشتیبانِ قبلی را انتخاب کن', 'Choose a previous backup file')
k('backupLast', 'آخرین پشتیبان: {date}', 'Last backup: {date}')
k('backupNever', 'هنوز پشتیبان نگرفته‌ای', "You haven't made a backup yet")
k('backupExported', 'پشتیبان ذخیره شد ✓', 'Backup saved ✓')
k('backupAuto', 'پشتیبان خودکار هفتگی', 'Automatic weekly backup')
k('backupAutoSub', 'تا ۵ نسخه در حافظه‌ی خصوصی برنامه نگه داشته می‌شود (Pro).', 'Keeps up to 5 copies in private app storage (Pro).')
k('backupAdvancedExport', 'خروجی‌های بیشتر (Pro)', 'More export formats (Pro)')
k('exportCsv', 'خروجی CSV', 'Export CSV')
k('exportText', 'خروجی متنی (Markdown)', 'Export text (Markdown)')
k('exportSaved', 'فایل ذخیره شد ✓', 'File saved ✓')
k('restoreConfirmTitle', 'بازیابی اطلاعات؟', 'Restore data?')
k('restoreConfirmReplace', 'اطلاعات فعلی ({current} مورد) با محتوای فایل ({incoming} مورد، ساخته‌شده در {date}) جایگزین می‌شود.\nپیش از آن یک نسخه‌ی ایمنی از اطلاعات فعلی نگه داشته می‌شود.', 'Your current data ({current} items) will be replaced by the file ({incoming} items, created {date}).\nA safety copy of the current data is kept first.')
k('restoreConfirmEmpty', 'فایل شامل {incoming} مورد است (ساخته‌شده در {date}).', 'The file contains {incoming} items (created {date}).')
k('restoreAction', 'بازیابی', 'Restore')
k('restoreDone', 'اطلاعات بازیابی شد ✓', 'Data restored ✓')
k('restoreProRestored', 'اشتراک Pro هم از پشتیبان بازیابی شد.', 'Your Pro subscription was restored too.')
k('backupErrEmpty', 'فایل خالی است.', 'The file is empty.')
k('backupErrTooLarge', 'فایل خیلی بزرگ است.', 'The file is too large.')
k('backupErrNotJson', 'فایل خراب یا ناقص است.', 'The file is damaged or incomplete.')
k('backupErrNotBackup', 'این فایل پشتیبان «بعداً» نیست.', 'This is not a Later backup file.')
k('backupErrMissing', 'فایل ناقص است.', 'The file is incomplete.')
k('backupErrFuture', 'این پشتیبان با نسخه‌ی جدیدتری از برنامه ساخته شده. برنامه را به‌روزرسانی کن.', 'This backup was made by a newer version of the app. Please update the app.')
k('backupErrUnsupported', 'قالب این پشتیبان دیگر پشتیبانی نمی‌شود.', 'This backup format is no longer supported.')
k('backupErrChecksum', 'فایل آسیب دیده یا ویرایش شده است.', 'The file is damaged or has been modified.')
k('backupErrInvalid', 'محتوای فایل معتبر نیست.', 'The file contents are not valid.')
k('backupErrMigration', 'به‌روزرسانی قالب فایل ناموفق بود.', 'Upgrading the file format failed.')
k('backupErrGeneric', 'بازیابی انجام نشد. اطلاعات فعلی دست‌نخورده ماند.', 'Restore failed. Your current data was not changed.')
k('backupNoChange', 'اطلاعات فعلی تغییری نکرد.', 'Your current data was not changed.')

# -------------------------------------------------------------------- Pro
k('proTitle', 'بعداً Pro', 'Later Pro')
k('proHeadline', 'امکانات بیشتر برای کسانی که «بعداً» را زیاد استفاده می‌کنند.', 'More power for people who use Later a lot.')
k('proFreeNote', 'نسخه‌ی رایگان همچنان کامل قابل استفاده است و هیچ اطلاعاتی محدود یا حذف نمی‌شود.', 'The free version stays fully usable and none of your data is ever limited or deleted.')
k('proActiveUntil', 'فعال تا {date}', 'Active until {date}')
k('proRemaining', '{n} روز باقی مانده', '{n} days left')
k('proExpiredNote', 'اشتراک Pro تمام شده؛ اطلاعاتت سالم است و فقط امکانات Pro غیرفعال شده‌اند.', 'Your Pro has ended. Your data is safe; only Pro features are switched off.')
k('proPlan1', '۱ ماهه', '1 month')
k('proPlan3', '۳ ماهه', '3 months')
k('proPlan6', '۶ ماهه', '6 months')
k('proPlanDay1', '۱ روزه (آزمایشی)', '1 day (test)')
k('proPlanDay7', '۷ روزه (آزمایشی)', '7 days (test)')
k('priceToman', '{price} تومان', '{price} Toman')
k('proBuy', 'خرید', 'Buy')
k('proExtend', 'تمدید', 'Extend')
k('proStackNote', 'با خرید جدید، روزهای باقی‌مانده حفظ می‌شود و مدت تازه به آن اضافه می‌شود.', 'A new purchase keeps your remaining days and adds the new period on top.')
k('proRestore', 'بازیابی خریدها', 'Restore purchases')
k('proRestored', '{n} خرید بازیابی شد', '{n} purchase(s) restored')
k('proNothingToRestore', 'خرید بازیابی‌نشده‌ای پیدا نشد.', 'No unrestored purchases found.')
k('proPurchaseSuccess', 'Pro فعال شد 🎉', 'Pro activated 🎉')
k('proPurchaseCancelled', 'خرید لغو شد.', 'Purchase cancelled.')
k('proPurchaseUnavailable', 'سرویس پرداخت در دسترس نیست. برنامه‌ی کافه‌بازار را بررسی کن.', 'Billing is unavailable. Check the Cafe Bazaar app.')
k('proPurchaseFailed', 'خرید انجام نشد. دوباره تلاش کن.', 'The purchase failed. Please try again.')
k('proTamper', 'اطلاعات اشتراک معتبر نبود و بازنشانی شد. اگر خرید کرده‌ای، «بازیابی خریدها» را بزن.', 'Subscription data was invalid and was reset. If you purchased, tap "Restore purchases".')
k('proF1', 'پیشنهاد هوشمند پیشرفته', 'Advanced smart pick')
k('proF2', 'فیلترها و جستجوی پیشرفته', 'Smart filters & advanced search')
k('proF3', 'آمار و تاریخچه‌ی کامل', 'Full statistics & history')
k('proF4', 'دسته‌های سفارشی بیشتر', 'More custom categories')
k('proF5', 'یادآوری تکرارشونده و پیشرفته', 'Recurring & advanced reminders')
k('proF6', 'ویجت‌های پیشرفته', 'Advanced widgets')
k('proF7', 'تم‌ها و آیکون‌های بیشتر', 'More themes & icons')
k('proF8', 'پشتیبان خودکار و خروجی‌های بیشتر', 'Auto backups & more exports')
k('proLockedTitle', 'این امکان مخصوص Pro است', 'This is a Pro feature')
k('proLockedBody', 'با Pro این و چند امکان دیگر باز می‌شود. نسخه‌ی رایگان همچنان کامل است.', 'Pro unlocks this and more. The free version remains complete.')
k('proSeePlans', 'دیدن پلن‌ها', 'See plans')
k('notNow', 'حالا نه', 'Not now')

# ------------------------------------------------------------- QA tools
k('qaTitle', 'ابزار تست (فقط نسخه‌ی آزمایشی)', 'Test tools (test build only)')
k('qaNote', 'این بخش در نسخه‌ی بازار وجود ندارد.', 'This section does not exist in the store build.')
k('qaGrantPlan', 'شبیه‌سازی خرید {plan}', 'Simulate buying {plan}')
k('qaClearPro', 'حذف Pro', 'Remove Pro')
k('qaAdvance', 'جلو بردن ساعت برنامه: {n} روز', 'Advance app clock: {n} days')
k('qaResetTime', 'بازنشانی ساعت شبیه‌سازی‌شده', 'Reset simulated clock')
k('qaClock', 'ساعت برنامه: {date}', 'App clock: {date}')
k('qaSeed', 'افزودن {n} مورد نمونه', 'Add {n} sample items')
k('qaSeedShelves', 'نمونه‌ی قفسه‌ها، آدم‌ها و کپسول', 'Sample shelves, people and capsule')
k('qaSeeded', '{n} مورد اضافه شد.', '{n} items added.')
k('qaNotifNow', 'اعلان همین حالا', 'Notification now')
k('qaNotifIn', 'اعلان تا {s} ثانیه‌ی دیگر', 'Notification in {s} seconds')
k('qaProState', 'وضعیت Pro: {state}', 'Pro state: {state}')

# ---------------------------------------------------- notifications & misc
k('notifChannelName', 'یادآوری‌ها', 'Reminders')
k('notifChannelDescription', 'یادآوری موردهایی که برای بعداً گذاشته‌ای', 'Reminders for the items you kept for later')
k('notifActionDone', 'انجام شد', 'Done')
k('notifActionTomorrow', 'فردا', 'Tomorrow')
k('notifPrivateBody', 'یه مورد منتظر توست', 'An item is waiting for you')
k('notifBodyGeneric', 'بعداً', 'Later')
k('notifTestTitle', 'اعلان آزمایشی', 'Test notification')
k('notifTestBody', 'اگر این را می‌بینی، اعلان‌ها کار می‌کنند ✓', "If you can see this, notifications work ✓")
k('reminderPermissionBanner', 'اجازه‌ی اعلان داده نشده؛ یادآوری‌ها نمایش داده نمی‌شوند.', "Notification permission isn't granted; reminders won't show.")
k('reminderSyncFailed', 'برخی یادآوری‌ها ثبت نشدند.', "Some reminders couldn't be scheduled.")
k('reminderApproximate', 'یادآوری‌ها تقریبی‌اند؛ برای دقت بیشتر «هشدار دقیق» را مجاز کن.', 'Reminders are approximate; allow "exact alarms" for better accuracy.')
k('permissionDeniedTitle', 'اجازه‌ی اعلان لازم است', 'Notification permission needed')
k('permissionDeniedBody', 'برای اینکه بعداً بتونم یادت بندازم، اجازه‌ی اعلان را فعال کن.', 'Enable notifications so I can remind you later.')
k('openSettings', 'باز کردن تنظیمات', 'Open settings')
k('shareAdded', '«{title}» به بعداً اضافه شد', '"{title}" added to Later')
k('widgetWaiting', '{n} مورد منتظرند', '{n} waiting')
k('widgetEmpty', 'چیزی منتظر نیست 🌱', 'Nothing waiting 🌱')
k('widgetAdd', '+ اضافه کن', '+ Add')
k('widgetPick', '🎯 پیشنهاد', '🎯 Pick')
k('widgetProOnly', 'ویجت پیشرفته مخصوص Pro است', 'The advanced widget is a Pro feature')
k('widgetSuggestion', 'پیشنهاد', 'Suggestion')
k('shortcutAdd', 'اضافه کردن', 'Add')
k('shortcutPick', 'یه مورد بهم بده', 'Give me one')
k('shortcutSearch', 'جستجو', 'Search')
k('licensesLegalese', 'ساخته‌شده با فلاتر. فونت وزیرمتن (مجوز OFL).', 'Built with Flutter. Vazirmatn font (OFL).')



# =====================================================================
# v2: nine new shelves + rewritten copy (plain, human tone).
# `o()` replaces the text of an existing key, `k()` adds a new one.
# =====================================================================
def o(key, fa, en):
    assert key in T, key
    d = T[key][2]
    T[key] = (fa, en, d)

# ---- rewritten copy: shorter, less "app-speak"
o('onb1Body', 'لازم نیست همه‌چیز همین الان تموم بشه. چیزی که وقتش نیست رو بذار کنار.', "Not everything has to be done right now. Put aside what isn't for now.")
o('onb2Body', 'مقاله، فیلم، خرید، ایده، یه تماس. بنویس، یا از هر برنامه‌ای «اشتراک‌گذاری» رو بزن.', 'An article, a movie, something to buy, an idea, a call. Type it, or hit Share in any app.')
o('onb3Body', 'تاریخ و ساعت بده تا خودش یادآوری کنه. ندادی هم مهم نیست، وقتی وقت داشتی قرعه بزن.', "Give it a date and it'll remind you. No date? Spin the roulette when you have a moment.")
o('onb4Body', 'اطلاعاتت فقط روی گوشی خودته و بدون اینترنت هم کار می‌کنه.', 'Your data stays on your phone and works without internet.')
o('onb5Body', 'هر چی الان وقتش نیست رو همین‌جا بذار.', "Put anything that isn't for now right here.")
o('homeWaiting', '{count} چیز منتظرته', '{count} things are waiting for you')
o('homeWaitingOne', 'یه چیز منتظرته', 'One thing is waiting for you')
o('pickCardTitle', 'قرعه بعداً', 'Later roulette')
o('pickCardSub', 'نمی‌دونی الان چی‌کار کنی؟ بذار قرعه تصمیم بگیره.', "Can't decide what to do? Let the roulette choose.")
o('staleNoPressure', 'عجله‌ای نیست. هر تصمیمی بگیری درسته.', 'No rush. Whatever you decide is fine.')
o('staleAllDone', 'همه‌چی مرتبه', 'All clear')
o('staleQuestion', 'این {days} روزه منتظرته.\nهنوز می‌خوای نگهش داری؟', "It's been waiting {days} days.\nDo you still want to keep it?")
o('decideDoneToast', 'انجام شد ✓', 'Done ✓')
o('proHeadline', 'اگه زیاد از «بعداً» استفاده می‌کنی، Pro کارت رو راحت‌تر می‌کنه.', 'If you use Later a lot, Pro makes it easier.')
o('proFreeNote', 'نسخه‌ی رایگان ناقص نیست. اگه Pro تموم بشه هم چیزی از اطلاعاتت پاک یا قفل نمی‌شه.', "The free version isn't crippled. If Pro ends, nothing you saved is deleted or locked.")
o('proStackNote', 'اگه وسط اشتراک دوباره بخری، روزهای مونده از بین نمی‌رن؛ مدت جدید بهشون اضافه می‌شه.', "If you buy again during a plan, your remaining days aren't lost; the new period is added on top.")
o('proLockedBody', 'این یکی مال Pro ـه. بقیه‌ی برنامه بدون Pro هم کامل کار می‌کنه.', 'This one is part of Pro. Everything else works fully without it.')
o('proExpiredNote', 'اشتراک Pro تموم شده. اطلاعاتت سر جاشه؛ فقط قابلیت‌های Pro خاموش شدن.', 'Your Pro has ended. Your data is still here; only the Pro features are off.')
o('proPurchaseSuccess', 'Pro فعال شد', 'Pro is active')
o('proRestored', '{n} خرید برگشت', '{n} purchase(s) restored')
o('proTamper', 'اطلاعات اشتراک درست نبود و پاک شد. اگه خرید کرده بودی «بازیابی خریدها» رو بزن.', 'The subscription data was invalid and was cleared. If you had bought Pro, tap "Restore purchases".')
o('aboutBody', 'بعداً جای چیزهاییه که الان وقتشون نیست. بدون حساب کاربری، بدون سرور.', "Later is where things go when it isn't the time yet. No account, no server.")
o('backupIntro', 'اطلاعاتت فقط روی همین گوشیه. قبل از عوض کردن گوشی یا نصب دوباره، یه فایل پشتیبان بگیر.', 'Your data lives only on this phone. Before switching phones or reinstalling, make a backup file.')
o('keepHistorySub', 'کارهای انجام‌شده و کنار گذاشته‌شده تو تاریخچه بمونن.', 'Keep finished and set-aside items in history.')
o('notifBodyGeneric', 'بعداً', 'Later')
o('reminderPermissionBanner', 'اجازه‌ی اعلان داده نشده، برای همین یادآوری‌ها نمایش داده نمی‌شن.', "Notifications aren't allowed, so reminders won't show.")
o('proF1', 'قرعه‌ی هوشمند و صندوق ورودی هوشمند', 'Smart roulette and smart inbox')
o('proF2', 'جستجو و فیلتر پیشرفته', 'Advanced search and filters')
o('proF3', 'آمار و تاریخچه‌ی کامل', 'Full statistics and history')
o('proF4', 'دسته‌ی سفارشی بیشتر', 'More custom categories')
o('proF5', 'یادآوری تکرارشونده', 'Repeating reminders')
o('proF6', 'ویجت لیستی', 'List widget')
o('proF7', 'رنگ و آیکون بیشتر', 'More colours and icons')
o('proF8', 'پشتیبان خودکار و خروجی CSV', 'Auto backup and CSV export')
o('decideLabel', 'قرعه این شد', 'The roulette picked')
o('smartPickProHint', 'فیلتر دسته و اولویت با Pro', 'Category and priority filters need Pro')
o('legalIntro', 'قبل از شروع، قوانین استفاده و سیاست حریم خصوصی رو بخون و تأیید کن.', 'Before you start, please read and accept the Terms of Use and Privacy Policy.')
o('errorGeneric', 'یه مشکلی پیش اومد. دوباره امتحان کن.', 'Something went wrong. Please try again.')
o('resetConfirmBody', 'همه‌ی موردها، دسته‌ها، تاریخچه و تنظیمات این برنامه برای همیشه پاک می‌شه و برنمی‌گرده. اشتراک Pro از بین نمی‌ره. بهتره اول یه پشتیبان بگیری.', "Everything in this app is deleted for good and can't be brought back. Your Pro plan isn't affected. Make a backup first.")
o('categoryLimit', 'نسخه‌ی رایگان {free} دسته‌ی سفارشی داره. با Pro تا {pro} تا می‌شه.', 'The free plan allows {free} custom categories. Pro allows up to {pro}.')
o('historyProNote', 'تاریخچه‌ی کامل (ماه و همه‌ی زمان‌ها) با Pro', 'Full history (month and all time) with Pro')
o('statsProLocked', 'آمار کامل با Pro', 'Full statistics with Pro')

# ---- new: generic
k('repeatYearly', 'هر سال', 'Every year')
k('defaultCapsuleTitle', 'کپسول بی‌نام', 'Untitled capsule')
k('defaultMessageTitle', 'پیام بی‌نام', 'Untitled message')
k('_select_typeName', '{id, select, task{کار} read{مقاله} watch{ویدیو} wishlist{خرید} idea{ایده} person{آدم} capsule{کپسول} future{پیام} app{نرم‌افزار} podcast{پادکست} course{دوره} game{بازی} other{مورد}}', '{id, select, task{Task} read{Article} watch{Video} wishlist{Wish} idea{Idea} person{Person} capsule{Capsule} future{Message} app{App} podcast{Podcast} course{Course} game{Game} other{Item}}')
k('daysAgo', '{n} روز پیش', '{n} days ago')

# ---- dashboard
k('dashRoulette', 'قرعه بعداً', 'Later roulette')
k('dashInbox', 'صندوق ورودی', 'Inbox')
k('dashInboxCount', '{n} مورد منتظر مرتب شدنه', '{n} items waiting to be sorted')
k('dashInboxEmpty', 'صندوقت خالیه', 'Your inbox is empty')
k('dashShelves', 'قفسه‌ها', 'Shelves')
k('shelfReadTitle', 'بعداً بخون', 'Read later')
k('shelfWatchTitle', 'بعداً ببین', 'Watch later')
k('shelfWishTitle', 'بعداً بخر', 'Wishlist')
k('shelfIdeaTitle', 'ایده‌ها', 'Ideas')
k('shelfPeopleTitle', 'آدم‌ها', 'People')
k('shelfFutureTitle', 'آینده', 'Future')
k('returnedBanner', 'یه چیز از گذشته برگشته', 'Something came back from the past')
k('returnedBannerBody', 'بازش کن ببین چی بوده.', 'Open it and see what it was.')
k('ideaReviewBanner', '{n} ایده وقت مرور دارن', '{n} ideas are due for review')

# ---- search
k('searchEverywhere', 'جستجو در همه‌چیز', 'Search everything')
k('searchEverywhereHint', 'کار، مقاله، ایده، آدم…', 'Tasks, articles, ideas, people…')
k('searchNothing', 'چیزی پیدا نشد', 'Nothing found')
k('searchStartTyping', 'یه کلمه بنویس.', 'Type a word.')
k('searchDone', 'انجام‌شده', 'Finished')

# ---- add sheet (types)
k('addTypeLabel', 'این چیه؟', "What is it?")
k('addTypeAuto', 'بعداً مرتبش می‌کنم', "I'll sort it later")
k('fieldPrice', 'قیمت', 'Price')
k('fieldCurrency', 'واحد پول', 'Currency')
k('currencyDefault', 'تومان', 'Toman')
k('fieldWatchKind', 'نوع', 'Kind')
k('kindVideo', 'ویدیو', 'Video')
k('kindMovie', 'فیلم', 'Movie')
k('kindSeries', 'سریال', 'Series')
k('kindOther', 'دیگر', 'Other')

# ---- stages
k('stageUnread', 'نخونده', 'Unread')
k('stageReading', 'دارم می‌خونم', 'Reading')
k('stageRead', 'خونده', 'Read')
k('stageArchived', 'بایگانی', 'Archived')
k('stageUnwatched', 'ندیده', 'Unwatched')
k('stageWatching', 'دارم می‌بینم', 'Watching')
k('stageWatched', 'دیده', 'Watched')
k('stageInterested', 'می‌خوامش', 'Interested')
k('stageMaybe', 'شاید', 'Maybe')
k('stageBought', 'خریدم', 'Bought')
k('stageNotInterested', 'دیگه نمی‌خوامش', 'No longer interested')
k('stageIdeaNew', 'تازه', 'New')
k('stageThinking', 'دارم فکر می‌کنم', 'Thinking')
k('stageDeveloping', 'دارم پرورشش می‌دم', 'Developing')
k('stageIdeaArchived', 'بایگانی', 'Archived')
k('stageIdeaDropped', 'ولش کردم', 'Dropped')
k('stageSealed', 'قفل', 'Sealed')
k('stageOpened', 'باز شده', 'Opened')
k('markAsRead', 'خوندم', 'Mark as read')
k('markAsWatched', 'دیدم', 'Mark as watched')
k('markAsBought', 'خریدم', 'Mark as bought')
k('itemStage', 'وضعیت', 'Status')
k('moveToShelf', 'منتقل کن به…', 'Move to…')
k('movedTo', 'رفت به «{shelf}»', 'Moved to "{shelf}"')

# ---- shelves
k('shelfEmptyReadTitle', 'هنوز چیزی برای خوندن نذاشتی', 'Nothing to read yet')
k('shelfEmptyReadBody', 'لینک مقاله رو با «اشتراک‌گذاری» بفرست به بعداً.', 'Share an article link to Later.')
k('shelfEmptyWatchTitle', 'هنوز ویدیویی نذاشتی', 'Nothing to watch yet')
k('shelfEmptyWatchBody', 'لینک یوتیوب یا اسم یه فیلم رو اینجا نگه دار.', 'Keep a YouTube link or a movie title here.')
k('shelfEmptyWishTitle', 'فهرست خریدت خالیه', 'Your wishlist is empty')
k('shelfEmptyWishBody', 'چیزی که شاید بخوای بخری رو اینجا بذار. بعد از یه مدت می‌پرسم هنوز می‌خوایش یا نه.', "Put something you might buy here. After a while I'll ask if you still want it.")
k('shelfEmptyIdeaTitle', 'هنوز ایده‌ای نذاشتی', 'No ideas yet')
k('shelfEmptyIdeaBody', 'ایده‌ها اینجا می‌مونن تا وقتش برسه.', 'Ideas wait here until their time comes.')
k('shelfWaiting', 'در انتظار', 'Waiting')
k('shelfHistory', 'تاریخچه', 'History')
k('shelfAllStages', 'همه', 'All')
k('shelfStatsTitle', 'آمار', 'Statistics')
k('shelfAdvancedFilters', 'فیلتر پیشرفته', 'Advanced filters')
k('shelfHistoryPro', 'تاریخچه‌ی این قفسه با Pro', "This shelf's history with Pro")
k('shelfCollections', 'فهرست‌ها', 'Lists')
k('shelfCollectionMain', 'اصلی', 'Main')
k('collectionNew', 'فهرست جدید', 'New list')
k('collectionName', 'اسم فهرست', 'List name')
k('collectionProHint', 'چند فهرست جدا با Pro', 'Several separate lists with Pro')
k('sortByPrice', 'قیمت', 'Price')
k('sortByScore', 'امتیاز', 'Score')
k('sortByTime', 'زمان تخمینی', 'Estimated time')
k('statsWaiting', 'در انتظار', 'Waiting')
k('statsFinished', 'تموم‌شده', 'Finished')
k('statsThisMonth', 'این ماه', 'This month')
k('statsMinutesWaiting', 'زمان کل منتظر', 'Total time waiting')
k('statsAvgFinish', 'میانگین تا تموم شدن', 'Average until finished')
k('statsTotalPrice', 'جمع قیمت‌ها', 'Total price')
k('readTimeEstimate', 'حدود {n} دقیقه', 'About {n} min')
k('linkHost', 'از {host}', 'from {host}')

# ---- wishlist / ideas
k('priceNow', 'قیمت', 'Price')
k('priceSetNew', 'ثبت قیمت تازه', 'Record a new price')
k('priceTarget', 'قیمت هدف', 'Target price')
k('priceTargetReached', 'به قیمت هدفت رسیده', 'Target price reached')
k('priceHistoryTitle', 'تاریخچه‌ی قیمت', 'Price history')
k('priceHistoryEmpty', 'هنوز قیمتی ثبت نشده.', 'No price recorded yet.')
k('priceHint', 'مثلاً ۱۲۰۰۰۰۰', 'e.g. 1200000')
k('wishProHint', 'قیمت هدف و تاریخچه‌ی قیمت با Pro', 'Target price and price history with Pro')
k('wishReviewTitle', 'واقعاً هنوز می‌خوایش؟', 'Do you still want it?')
k('wishReviewQuestion', 'این {days} روزه تو فهرستته.\nهنوز می‌خوای بخریش؟', "It's been on your list for {days} days.\nDo you still want to buy it?")
k('wishStill', 'هنوز می‌خوام', 'I still want it')
k('wishUnsure', 'مطمئن نیستم', "I'm not sure")
k('wishNo', 'دیگه نمی‌خوام', "I don't want it anymore")
k('ideaReviewTitle', 'مرور ایده‌ها', 'Idea review')
k('ideaReviewNone', 'چیزی برای مرور نیست.', 'Nothing to review.')
k('ideaReviewIntro', 'هر ایده رو یه نگاه بنداز و بگو چیکارش کنیم.', 'Take a look at each idea and decide what to do.')
k('ideaScore', 'امتیاز', 'Score')
k('ideaLinks', 'ایده‌های مرتبط', 'Related ideas')
k('ideaAddLink', 'وصل کن به یه ایده‌ی دیگه', 'Link another idea')
k('ideaToTask', 'تبدیل به کار', 'Turn into a task')
k('ideaConverted', 'حالا یه کاره', "It's a task now")
k('ideaKeepThinking', 'هنوز فکر می‌کنم', "Still thinking")
k('ideaDevelop', 'می‌خوام پرورشش بدم', "Let's develop it")
k('ideaArchiveIt', 'بایگانی', 'Archive')
k('ideaDropIt', 'ولش کن', 'Let it go')
k('ideaLastReviewed', 'آخرین مرور: {when}', 'Last reviewed: {when}')
k('ideaNeverReviewed', 'هنوز مرور نشده', 'Not reviewed yet')
k('ideaProHint', 'امتیاز، اتصال ایده‌ها و مرور با Pro', 'Score, linking and review with Pro')

# ---- people
k('peopleTitle', 'آدم‌ها', 'People')
k('peopleEmptyTitle', 'هنوز کسی رو اضافه نکردی', "You haven't added anyone yet")
k('peopleEmptyBody', 'مثلاً «بعداً به علی زنگ بزن». آدم رو از مخاطب‌ها انتخاب کن یا اسمش رو بنویس.', 'For example "call Ali later". Pick someone from your contacts or type a name.')
k('personAdd', 'آدم جدید', 'Add a person')
k('personFromContacts', 'انتخاب از مخاطب‌ها', 'Pick from contacts')
k('personTypeName', 'فقط اسم بنویسم', 'Just type a name')
k('personName', 'اسم', 'Name')
k('personNote', 'یادداشت', 'Note')
k('personLast', 'آخرین ارتباط: {when}', 'Last contact: {when}')
k('personNever', 'هنوز ارتباطی ثبت نشده', 'No contact logged yet')
k('personNext', 'بعدی: {when}', 'Next: {when}')
k('personNoNext', 'یادآوری‌ای نداره', 'No reminder')
k('personTalked', 'همین الان صحبت کردیم', 'We just talked')
k('personAddReminder', 'یادآوری تازه', 'New reminder')
k('personReminderHint', 'مثلاً: پیام بده', 'e.g. send a message')
k('personOpenContact', 'باز کردن مخاطب', 'Open contact')
k('personDeleteTitle', 'این آدم حذف بشه؟', 'Delete this person?')
k('personDeleteBody', 'یادآوری‌هاش می‌مونن ولی دیگه به این آدم وصل نیستن.', "Its reminders stay, but they're no longer linked to this person.")
k('personHistory', 'تاریخچه‌ی ارتباط', 'Contact history')
k('personFollowUp', 'پیگیری', 'Follow up')
k('personFollowUpDays', 'بعد از {n} روز یادم بنداز', 'Remind me in {n} days')
k('personGroup', 'گروه', 'Group')
k('personDueTitle', 'باید سر بزنی', 'Time to reach out')
k('personLinked', 'یادآوری‌ها', 'Reminders')
k('personPickerFailed', 'انتخاب مخاطب انجام نشد. اسم رو دستی بنویس.', "Couldn't pick a contact. Type the name instead.")
k('interactionNoteHint', 'چی گفتید؟ (اختیاری)', 'What did you talk about? (optional)')
k('peopleProHint', 'تاریخچه، پیگیری و «باید سر بزنی» با Pro', 'History, follow-ups and "time to reach out" with Pro')
k('personContactRef', 'از مخاطب‌های گوشی', 'From your contacts')

# ---- future (capsules + messages)
k('futureTitle', 'آینده', 'Future')
k('futureTabCapsules', 'کپسول زمانی', 'Time capsules')
k('futureTabMessages', 'پیام به خودم', 'Messages to me')
k('capsuleEmptyTitle', 'کپسولی نداری', 'No capsules')
k('capsuleEmptyBody', 'چیزی رو تا یه تاریخ از جلوی چشمت بردار. همون روز برمی‌گرده.', "Hide something until a date. It comes back that day.")
k('messageEmptyTitle', 'پیامی ننوشتی', "You haven't written any message")
k('messageEmptyBody', 'برای خودِ آینده‌ات بنویس.', 'Write to your future self.')
k('capsuleNew', 'کپسول جدید', 'New capsule')
k('messageNew', 'پیام جدید', 'New message')
k('sealTitleHint', 'عنوان', 'Title')
k('capsuleBodyHint', 'چی رو می‌خوای بعداً ببینی؟', 'What do you want to see later?')
k('messageBodyHint', 'به خودِ آینده‌ات چی می‌گی؟', 'What do you tell your future self?')
k('sealOpenOn', 'باز می‌شه: {date}', 'Opens: {date}')
k('sealPickDate', 'تاریخ باز شدن', 'Opening date')
k('sealQuick1m', '۱ ماه دیگه', 'In 1 month')
k('sealQuick3m', '۳ ماه دیگه', 'In 3 months')
k('sealQuick6m', '۶ ماه دیگه', 'In 6 months')
k('sealQuick1y', '۱ سال دیگه', 'In 1 year')
k('sealSaved', 'قفل شد. تا {date} دیده نمی‌شه.', "Sealed. You won't see it until {date}.")
k('sealLimitFree', 'نسخه‌ی رایگان همزمان تا {n} مورد قفل‌شده داره. با Pro نامحدوده.', 'The free plan allows {n} sealed items at a time. Pro is unlimited.')
k('sealNeedsFuture', 'تاریخ باید توی آینده باشه.', 'The date must be in the future.')
k('lockedUntil', 'تا {date} قفله', 'Locked until {date}')
k('openIt', 'بازش کن', 'Open it')
k('returnedTitle', 'یه چیز از گذشته برای تو برگشته', 'Something came back from the past')
k('messageReturnedTitle', 'پیامی از خودِ گذشته‌ات داری', 'You have a message from your past self')
k('writtenOn', 'نوشته‌شده در {date}', 'Written on {date}')
k('sealRepeat', 'تکرار', 'Repeat')
k('sealAttach', 'پیوست', 'Attachments')
k('sealAttachAdd', 'افزودن عکس یا فایل', 'Add a photo or file')
k('sealAttachLimit', 'تا {n} فایل، هر کدوم حداکثر {mb} مگابایت. فقط روی همین گوشی می‌مونه.', 'Up to {n} files, {mb} MB each. They stay on this phone only.')
k('sealAttachTooBig', 'این فایل از حد مجاز بزرگ‌تره.', 'This file is over the size limit.')
k('sealAttachFailed', 'فایل اضافه نشد.', "The file couldn't be added.")
k('sealProHint', 'کپسول و پیام نامحدود، پیوست، برچسب و تکرار با Pro', 'Unlimited capsules and messages, attachments, tags and repeats with Pro')
k('sealThisItem', 'برای آینده نگه دار', 'Keep for the future')
k('sealItemQuestion', 'تا کِی نبینمش؟', 'Hide it until when?')
k('timelineOpened', 'باز شده در {date}', 'Opened on {date}')
k('notifCapsuleTitle', 'یه چیز از گذشته برای تو برگشته', 'Something came back from the past')
k('notifCapsuleBody', 'بازش کن ببین چی بوده.', 'Open it and see what it was.')
k('notifFutureTitle', 'پیامی از خودِ گذشته‌ات داری', 'You have a message from your past self')
k('notifFutureBody', 'بازش کن و بخونش.', 'Open it and read it.')
k('notifIdeaReviewTitle', 'وقت مرور ایده‌هاست', 'Time to review your ideas')
k('notifIdeaReviewBody', 'چند تا ایده منتظر یه نگاه دوباره‌ان.', 'A few ideas are waiting for another look.')

# ---- inbox
k('inboxTitle', 'صندوق ورودی', 'Inbox')
k('inboxIntro', 'هر چی سریع ذخیره کردی اینجا می‌مونه تا تکلیفش رو روشن کنی.', 'Whatever you saved quickly waits here until you decide what to do with it.')
k('inboxEmptyTitle', 'صندوق خالیه', 'The inbox is empty')
k('inboxEmptyBody', 'همه‌چیز جای خودشه.', 'Everything is in its place.')
k('triageToday', 'امروز', 'Today')
k('triageWeek', 'این هفته', 'This week')
k('triageNoDate', 'بدون تاریخ', 'No date')
k('triageRead', 'بعداً بخون', 'Read later')
k('triageWatch', 'بعداً ببین', 'Watch later')
k('triageWish', 'بعداً بخر', 'Wishlist')
k('triageIdea', 'ایده', 'Idea')
k('triageDone', 'انجام شد', 'Done')
k('triageDelete', 'حذف', 'Delete')
k('inboxSuggest', 'شبیه {what} به نظر می‌رسه. منتقل بشه؟', 'This looks like {what}. Move it?')
k('inboxSuggestYes', 'آره، منتقل کن', 'Yes, move it')
k('suggestWhatRead', 'یه مقاله', 'an article')
k('suggestWhatWatch', 'یه ویدیو', 'a video')
k('suggestWhatWish', 'یه چیز برای خرید', 'something to buy')
k('suggestWhatIdea', 'یه ایده', 'an idea')
k('suggestWhatPerson', 'یه یادآوری برای یه آدم', 'a reminder about a person')
k('inboxProHint', 'پیشنهاد خودکار مقصد با Pro', 'Automatic destination suggestions with Pro')

# ---- roulette
k('rouletteTitle', 'قرعه بعداً', 'Later roulette')
k('roulettePick', 'انتخاب کن', 'Pick one')
k('rouletteSpinning', 'دارم انتخاب می‌کنم…', 'Picking…')
k('rouletteStart', 'شروع', 'Start')
k('rouletteLater', 'بعداً', 'Later')
k('rouletteAgain', 'یکی دیگه', 'Another one')
k('rouletteEmptyTitle', 'چیزی برای قرعه نیست', 'Nothing to draw from')
k('rouletteEmptyBody', 'لیستت خالیه یا چیزی با این فیلترها نمی‌خونه.', 'Your list is empty or nothing matches the filters.')
k('rouletteFilters', 'فیلترها', 'Filters')
k('rouletteTime', 'وقت', 'Time')
k('rouletteEnergy', 'حال و انرژی', 'Energy')
k('energyLow', 'کم‌حالم', 'Low')
k('energyHigh', 'سرحالم', 'High')
k('rouletteCats', 'دسته‌های قرعه', 'Roulette categories')
k('rouletteHistoryTitle', 'تاریخچه‌ی قرعه', 'Roulette history')
k('rouletteHistoryEmpty', 'هنوز قرعه‌ای نزدی.', "You haven't spun yet.")
k('rouletteProHint', 'فیلتر وقت، دسته، اولویت و انرژی و تاریخچه‌ی قرعه با Pro', 'Time, category, priority and energy filters and history with Pro')
k('rouletteOpenLink', 'باز کردن لینک', 'Open link')

# ---- share destination
k('shareWhere', 'کجا نگهش دارم؟', 'Where should I keep it?')
k('shareInbox', 'صندوق ورودی', 'Inbox')
k('shareSavedInbox', 'تو صندوق ورودی ذخیره شد.', 'Saved to your inbox.')
k('shareSuggested', 'پیشنهاد', 'Suggested')

# ---- Pro plan screen (what you get)
k('proWhatYouGet', 'با Pro چی می‌گیری', 'What you get with Pro')
k('proFreeHeader', 'تو نسخه‌ی رایگان هم داری', 'Free already includes')
k('proFreeList', 'ذخیره‌ی نامحدود، صندوق ورودی، قرعه‌ی پایه، بعداً بخون / ببین / بخر، ایده‌ها، آدم‌ها، کپسول و پیام (تا ۲ تا)، جستجو، یادآوری، اشتراک‌گذاری، تم روشن و تیره، پشتیبان‌گیری.', 'Unlimited saving, inbox, basic roulette, read / watch / wishlist, ideas, people, capsules and messages (up to 2), search, reminders, sharing, light and dark themes, backup.')
k('proFT1', 'قرعه‌ی هوشمند', 'Smart roulette')
k('proFD1', 'فقط از دسته‌های دلخواه، بر اساس وقت، اولویت و حال و انرژی‌ات انتخاب می‌کنه و تاریخچه‌ی قرعه‌ها رو نگه می‌داره.', 'Picks from the categories you choose, by time, priority and energy, and keeps a roulette history.')
k('proFT2', 'صندوق ورودی هوشمند', 'Smart inbox')
k('proFD2', 'برای هر مورد مقصد پیشنهاد می‌ده (مقاله، ویدیو، خرید، ایده). همیشه تأیید آخر با خودته.', 'Suggests a destination for each item (article, video, purchase, idea). You always confirm.')
k('proFT3', 'قفسه‌های کامل‌تر', 'Fuller shelves')
k('proFD3', 'تاریخچه و آمار خوندن و دیدن، فیلتر و مرتب‌سازی پیشرفته، چند فهرست جدا.', 'Reading and watching history and stats, advanced filters and sorting, several separate lists.')
k('proFT4', 'خرید حساب‌شده', 'Smarter wishlist')
k('proFD4', 'قیمت هدف، تاریخچه‌ی قیمتی که خودت ثبت کردی، آمار و یادآوری بررسی دوباره.', 'Target price, a price history you record, stats and re-check reminders.')
k('proFT5', 'ایده‌ها با مرور', 'Ideas with review')
k('proFD5', 'امتیاز، وصل کردن ایده‌ها به هم، مرور دوره‌ای، یادآوری ماهانه و تبدیل ایده به کار.', 'Scores, linking ideas, periodic review, a monthly reminder and turning an idea into a task.')
k('proFT6', 'آدم‌های مهم', 'People who matter')
k('proFD6', 'تاریخچه‌ی ارتباط، پیگیری خودکار، گروه‌های دلخواه و لیست «باید سر بزنی».', 'Contact history, automatic follow-ups, custom groups and a "time to reach out" list.')
k('proFT7', 'آینده‌ی بیشتر', 'More future')
k('proFD7', 'کپسول و پیام بی‌شمار، پیوست عکس و فایل کوچک، برچسب و تکرار (مثلاً هر سال).', 'Unlimited capsules and messages, small photo and file attachments, tags and repeats (e.g. yearly).')
k('proFT8', 'جستجو و فیلتر', 'Search and filters')
k('proFD8', 'جستجو تو برچسب، لینک و یادداشت و فیلتر «مانده‌ها».', 'Search in tags, links and notes, plus the "waiting long" filter.')
k('proFT9', 'آمار و تاریخچه‌ی کامل', 'Full stats and history')
k('proFD9', 'همه‌ی ماه‌ها و آمار کامل، به‌جای فقط ۷ روز اخیر.', 'All months and full statistics instead of only the last 7 days.')
k('proFT10', 'یادآوری تکرارشونده', 'Repeating reminders')
k('proFD10', 'روزانه، هفتگی، ماهانه یا سالانه، تا وقتی انجامش بدی.', 'Daily, weekly, monthly or yearly, until you do it.')
k('proFT11', 'ظاهر و ویجت', 'Look and widget')
k('proFD11', 'چند رنگ و آیکون دیگه و ویجت لیستی برای صفحه‌ی اصلی گوشی.', 'More colours and icons, and a list widget for your home screen.')
k('proFT12', 'پشتیبان‌گیری بیشتر', 'More backup')
k('proFD12', 'پشتیبان خودکار هفتگی و خروجی CSV و متن.', 'Weekly automatic backup and CSV / text export.')

# ---- settings
k('settingsRouletteCats', 'دسته‌های قرعه', 'Roulette categories')
k('settingsRouletteCatsAll', 'همه‌ی دسته‌ها', 'All categories')
k('wishlistReviewAfter', 'پرسیدن «هنوز می‌خوایش؟» بعد از', 'Ask "still want it?" after')
k('askWhereOnShare', 'بعد از اشتراک‌گذاری بپرس کجا بره', 'After sharing, ask where it goes')
k('askWhereOnShareSub', 'اگه خاموشه، همه‌چیز می‌ره تو صندوق ورودی.', "If off, everything goes to the inbox.")
k('ideaReviewEvery', 'مرور ایده‌ها هر', 'Review ideas every')
k('ideaReviewMonthly', 'یادآوری مرور ماهانه', 'Monthly review reminder')


def build(lang_idx):
    out = {'@@locale': ['fa', 'en'][lang_idx]}
    for key, (fa, en, desc) in T.items():
        text = (fa, en)[lang_idx]
        if key.startswith('_select_'):
            name = key[len('_select_'):]
            out[name] = text
            if lang_idx == 0:
                out['@' + name] = {'placeholders': {'id': {'type': 'String'}}}
            continue
        out[key] = text
        if lang_idx == 0:
            # placeholders come from the Persian (template) text
            names = sorted(set(re.findall(r'\{(\w+)\}', fa)))
            meta = {}
            if names:
                meta['placeholders'] = {n: {'type': 'String'} for n in names}
            if desc:
                meta['description'] = desc
            if meta:
                out['@' + key] = meta
    return out


# ============================================================ apps / podcasts / courses / games
k('shelfAppTitle', 'بعداً نصب کن', 'Install later')
k('shelfPodcastTitle', 'بعداً گوش بده', 'Listen later')
k('shelfCourseTitle', 'بعداً یاد بگیر', 'Learn later')
k('shelfGameTitle', 'بعداً بازی کن', 'Play later')
k('shelfAppSub', 'نرم‌افزارهایی که بعداً نصب می‌کنم', 'Apps I will install later')
k('shelfPodcastSub', 'پادکست‌هایی که بعداً گوش می‌کنم', 'Podcasts I will listen to later')
k('shelfCourseSub', 'دوره‌ها و مهارت‌هایی که بعداً یاد می‌گیرم', 'Courses and skills I will learn later')
k('shelfGameSub', 'بازی‌هایی که بعداً بازی می‌کنم', 'Games I will play later')
k('shelfEmptyAppTitle', 'هنوز نرم‌افزاری نذاشتی', 'No apps yet')
k('shelfEmptyAppBody', 'لینک Google Play یا بازار رو بفرست به بعداً، تا وقتی نصبش کنی اینجا می‌مونه.', 'Share a Play Store or Bazaar link to Later and it waits here until you install it.')
k('shelfEmptyPodcastTitle', 'هنوز پادکستی نذاشتی', 'No podcasts yet')
k('shelfEmptyPodcastBody', 'یه قسمت رو نگه دار تا وقتی وقت داشتی ادامه‌اش بدی.', 'Keep an episode and carry on whenever you have time.')
k('shelfEmptyCourseTitle', 'هنوز دوره‌ای نذاشتی', 'No courses yet')
k('shelfEmptyCourseBody', 'دوره یا آموزشی که می‌خوای بعداً یاد بگیری رو اینجا بذار و بنویس چرا.', 'Save a course you want to learn later and note why.')
k('shelfEmptyGameTitle', 'هنوز بازی‌ای نذاشتی', 'No games yet')
k('shelfEmptyGameBody', 'بازی‌هایی که می‌خوای یه روز بازی کنی رو اینجا جمع کن.', 'Collect the games you want to play one day.')

k('stageNotInstalled', 'نصب نشده', 'Not installed')
k('stageWantInstall', 'می‌خوام نصب کنم', 'Want to install')
k('stageEvaluating', 'در حال بررسی', 'Checking it out')
k('stageInstalled', 'نصب کردم', 'Installed')
k('stageAppNotWanted', 'دیگه نمی‌خوام', 'No longer wanted')
k('stageNotListened', 'گوش نکرده‌ام', 'Not listened')
k('stageListening', 'در حال گوش دادن', 'Listening')
k('stagePaused', 'متوقف شده', 'Paused')
k('stageListened', 'گوش دادم', 'Listened')
k('stageLearnLater', 'بعداً یاد می‌گیرم', 'Later')
k('stageLearning', 'در حال یادگیری', 'Learning')
k('stageLearned', 'تمام شد', 'Finished')
k('stageLearnAbandoned', 'رها کردم', 'Dropped')
k('stageWantPlay', 'می‌خوام بازی کنم', 'Want to play')
k('stagePlaying', 'در حال بازی', 'Playing')
k('stageGameFinished', 'تمام شد', 'Finished')
k('stageGameDropped', 'دیگه علاقه ندارم', 'Not interested')
k('markAsInstalled', 'نصبش کردم', 'I installed it')
k('markAsListened', 'گوش دادم', 'I listened')
k('markAsLearned', 'تمومش کردم', 'I finished it')

k('fieldPlatforms', 'پلتفرم', 'Platform')
k('platAndroid', 'اندروید', 'Android')
k('platWindows', 'ویندوز', 'Windows')
k('platMac', 'macOS', 'macOS')
k('platLinux', 'لینوکس', 'Linux')
k('platIos', 'iOS', 'iOS')
k('platWeb', 'وب', 'Web')
k('platOther', 'سایر', 'Other')
k('platformsProHint', 'چند پلتفرم برای یک نرم‌افزار با Pro', 'Several platforms per app with Pro')
k('fieldShow', 'نام پادکست', 'Podcast name')
k('fieldEpisodeHint', 'نام قسمت', 'Episode title')
k('fieldCreator', 'سازنده', 'Creator')
k('fieldInstructor', 'مدرس یا سازنده', 'Instructor or maker')
k('fieldGenre', 'ژانر', 'Genre')
k('fieldLevel', 'سطح', 'Level')
k('levelBeginner', 'مقدماتی', 'Beginner')
k('levelIntermediate', 'متوسط', 'Intermediate')
k('levelAdvanced', 'پیشرفته', 'Advanced')
k('fieldGoal', 'هدف من از یادگیری', 'Why I want to learn this')
k('goalHint', 'مثلاً: یادگیری Python برای ساخت AI', 'e.g. learn Python to build AI')
k('fieldDurationMin', 'مدت (دقیقه)', 'Length (minutes)')
k('fieldGameMin', 'مدت یک دور بازی (دقیقه)', 'Length of a session (minutes)')
k('fieldProgress', 'پیشرفت', 'Progress')
k('podcastProgress', '{p}٪ گوش داده شده', '{p}% listened')
k('podcastRemaining', '{t} باقی مانده', '{t} left')
k('learnProgress', '{p}٪ پیشرفت', '{p}% done')
k('continueListening', 'ادامه گوش دادن', 'Keep listening')
k('continueFromWhere', 'ادامه از جایی که ماندم', 'Continue where I left off')
k('lastPosition', 'آخرین نقطه', 'Last position')
k('lastPositionHint', 'مثلاً ۱۸:۳۲', 'e.g. 18:32')
k('openLinkApp', 'باز کردن لینک', 'Open link')
k('appStillNeed', 'آیا هنوز به این برنامه نیاز دارم؟', 'Do I still need this app?')
k('appReviewQuestion', 'این {days} روزه تو فهرستته.\nهنوز ارزش نصب کردن داره؟', "It's been on your list for {days} days.\nIs it still worth installing?")
k('appAnsInstalled', 'نصب کردم', 'I installed it')
k('appAnsStill', 'هنوز می‌خوام', 'Still want it')
k('appAnsLater', 'بعداً بررسی می‌کنم', "Ask me later")
k('appAnsNo', 'بی‌خیالش شدم', 'Forget it')
k('statusHistoryTitle', 'تاریخچه‌ی وضعیت', 'Status history')
k('statusHistoryPro', 'تاریخچه‌ی تغییر وضعیت با Pro', 'Status history comes with Pro')
k('appProHint', 'چند پلتفرم، مرور هوشمند، آمار و یادآوری مرور با Pro', 'Multiple platforms, smart review, stats and review reminders with Pro')
k('podcastProHint', 'صف هوشمند، قسمت‌های کوتاه و آمار گوش‌دادن با Pro', 'Smart queue, short episodes and listening stats with Pro')
k('learnProHint', 'هدف و برنامه، ثبت جلسه، رگه‌ی یادگیری و آمار با Pro', 'Goals, study sessions, streaks and stats with Pro')
k('gameProHint', 'فیلتر زمان و ژانر و پیشنهاد هوشمند بازی با Pro', 'Time and genre filters and a smart pick with Pro')
k('podcastQueueTitle', 'صف هوشمند', 'Smart queue')
k('shortEpisodes', 'کوتاه برای وقت آزاد', 'Short ones for spare time')
k('queueEmpty', 'قسمتی که به این وقت بخوره نیست.', 'Nothing fits this much time.')
k('continueSection', 'ادامه بده', 'Pick up where you left off')

k('sessionLog', 'ثبت جلسه', 'Log a session')
k('sessionMinutes', 'چند دقیقه؟', 'How many minutes?')
k('sessionsTitle', 'جلسه‌ها', 'Sessions')
k('sessionLogged', 'ثبت شد.', 'Logged.')
k('statsStreak', 'پشت‌سرهم', 'Streak')
k('streakDays', '{n} روز', '{n} days')
k('statsWeekMinutes', 'این هفته', 'This week')
k('statsTotalTime', 'جمع زمان', 'Total time')
k('minutesTotal', '{n} دقیقه', '{n} min')
k('learnGoalTitle', 'هدف و برنامه', 'Goal and plan')
k('goalDate', 'تا تاریخ', 'By')
k('weeklyGoal', 'هدف هفتگی (دقیقه)', 'Weekly target (minutes)')
k('weekGoalProgress', 'این هفته: {a} از {b} دقیقه', 'This week: {a} of {b} minutes')

k('gamePickTitle', 'امروز چی بازی کنم؟', 'What should I play today?')
k('gamePickBtn', 'یه بازی انتخاب کن', 'Pick a game')
k('gamePickLabel', 'امروز اینو بازی کن', 'Play this today')
k('gameHowLong', 'حدود {n} دقیقه وقت داری؟', 'Got about {n} minutes?')
k('gameStart', 'شروع', 'Start')
k('gameLater', 'بعداً', 'Later')
k('gameAnother', 'یکی دیگه', 'Another one')
k('gameEmptyTitle', 'بازی‌ای برای پیشنهاد نیست', 'No game to suggest')
k('gameEmptyBody', 'بازی اضافه کن یا فیلترها رو شل‌تر کن.', 'Add a game or loosen the filters.')
k('gameFreeTime', 'وقت آزاد', 'Free time')
k('gameStatusFilter', 'وضعیت', 'Status')
k('gameGenreFilter', 'ژانر', 'Genre')
k('gameStarted', 'برو بازی کن! حالا در حال بازی ثبتش کردم.', 'Have fun! Marked as playing.')

k('imgAdd', 'افزودن عکس', 'Add a picture')
k('imgTake', 'گرفتن عکس', 'Take a photo')
k('imgGallery', 'انتخاب از گالری', 'Choose from gallery')
k('imgChange', 'تغییر عکس', 'Change picture')
k('imgRemove', 'حذف عکس', 'Remove picture')
k('imgSetCover', 'عکس اصلی کن', 'Use as main picture')
k('imgCover', 'اصلی', 'Main')
k('imgGalleryTitle', 'عکس‌ها', 'Pictures')
k('imgTooBig', 'این عکس خیلی بزرگه (حداکثر ۳۰ مگابایت).', 'That picture is too large (30 MB max).')
k('imgInvalid', 'این فایل یه عکس معتبر نیست.', "That file isn't a valid picture.")
k('imgFailed', 'عکس اضافه نشد.', "Couldn't add the picture.")
k('imgProMore', 'چند عکس برای هر مورد با Pro', 'Several pictures per item with Pro')
k('imgAdded', 'عکس اضافه شد.', 'Picture added.')
k('imgRemoved', 'عکس حذف شد.', 'Picture removed.')
k('imgNone', 'عکسی نداری', 'No picture yet')
k('imgPrivacy', 'عکس‌ها فقط روی همین گوشی می‌مونن.', 'Pictures stay on this phone only.')

k('suggestWhatApp', 'یه نرم‌افزار', 'an app')
k('suggestWhatPodcast', 'یه پادکست', 'a podcast')
k('suggestWhatCourse', 'یه دوره', 'a course')
k('suggestWhatGame', 'یه بازی', 'a game')
k('triageMore', 'جای دیگه…', 'Somewhere else…')

k('settingsAppReview', 'یادآوری ماهانه‌ی مرور نرم‌افزارها', 'Monthly app review reminder')
k('notifAppReviewTitle', 'نرم‌افزارهای منتظر نصب', 'Apps waiting to be installed')
k('notifAppReviewBody', 'یه نگاه بنداز: هنوز همه‌شون رو می‌خوای؟', 'Take a look: do you still want them all?')

k('widgetTagline', 'الان لازم نیست؛ فراموشش نکن.', "Not now — just don't forget it.")
k('widgetInbox', 'صندوق ورودی', 'Inbox')
k('widgetToday', 'امروز', 'Today')
k('widgetLearn', 'یادگیری', 'Learn')
k('widgetPodcasts', 'گوش‌دادنی', 'Listen')
k('widgetGames', 'بازی‌ها', 'Games')
k('widgetWishlist', 'خرید', 'Wishlist')
k('widgetIdeas', 'ایده', 'Ideas')
k('widgetRefresh', 'تازه‌سازی', 'Refresh')
k('widgetNothing', 'فعلاً چیزی نیست', 'Nothing yet')
k('widgetSmartToday', '🎯 امروز شاید اینو انجام بدی:\n{t}', '🎯 You could do this today:\n{t}')
k('widgetSmartLearn', '📚 ادامه‌ی یادگیری:\n{t}', '📚 Keep learning:\n{t}')
k('widgetSmartListen', '🎧 ادامه بده:\n{t}', '🎧 Pick up:\n{t}')
k('widgetSmartFree', '🎧 برای وقت آزاد:\n{t} · {m} دقیقه', '🎧 For spare time:\n{t} · {m} min')
k('widgetSmartGame', '🎮 اگه {m} دقیقه وقت داری:\n{t}', '🎮 If you have {m} minutes:\n{t}')
k('widgetSmartWaiting', '⏳ مدتیه منتظره:\n{t}', '⏳ Has been waiting a while:\n{t}')
k('widgetQuickAdd', 'ذخیره‌ی سریع', 'Quick save')
k('captureHint', 'چی رو برای بعداً نگه دارم؟', 'What should I keep for later?')
k('captureSaved', 'ذخیره شد.', 'Saved.')
k('captureKinds', 'چه جور چیزیه؟', 'What kind of thing is it?')

# Pro plan descriptions for the new modules and pictures
k('proFT13', 'نرم‌افزارها با مرور', 'Apps with review')
k('proFD13', 'چند پلتفرم برای هر برنامه، مرور هوشمند، یادآوری ماهانه، آمار نصب‌شده و رهاشده و تاریخچه‌ی وضعیت.', 'Several platforms per app, smart review, a monthly reminder, installed/dropped stats and status history.')
k('proFT14', 'پادکست با صف هوشمند', 'Podcasts with a smart queue')
k('proFD14', 'صف مرتب بر اساس وقتت، فیلتر قسمت‌های کوتاه، آمار گوش‌دادن، تاریخچه و مرور.', 'A queue ordered for the time you have, short-episode filter, listening stats, history and review.')
k('proFT15', 'یادگیری با هدف', 'Learning with goals')
k('proFD15', 'هدف تاریخ‌دار و برنامه‌ی هفتگی، ثبت جلسه‌های مطالعه، زمان صرف‌شده، رگه‌ی روزانه و آمار.', 'Dated goals and a weekly plan, logged study sessions, time spent, daily streaks and stats.')
k('proFT16', 'بازی با پیشنهاد هوشمند', 'Games with a smart pick')
k('proFD16', 'پیشنهاد بر اساس وقت آزاد، ژانر، اولویت و وضعیت؛ تنوع ژانر، ثبت زمان بازی و آمار.', 'Picks by free time, genre, priority and status; genre variety, logged play time and stats.')
k('proFT17', 'گالری عکس', 'Picture gallery')
k('proFD17', 'تا ۸ عکس برای هر مورد، انتخاب عکس اصلی و نمایش بزرگ. یک عکس برای هر مورد رایگانه.', 'Up to 8 pictures per item, pick the main one and view it large. One picture per item is free.')

o('proFreeList', 'ذخیره‌ی نامحدود، صندوق ورودی، قرعه‌ی پایه، همه‌ی قفسه‌ها (مقاله، ویدیو، خرید، ایده، نرم‌افزار، پادکست، دوره، بازی)، آدم‌ها، کپسول و پیام (تا ۲ تا)، یه عکس برای هر مورد، جستجو، یادآوری، اشتراک‌گذاری، ویجت‌های خانه، تم روشن و تیره، پشتیبان‌گیری.', 'Unlimited saving, inbox, basic roulette, every shelf (articles, videos, wishlist, ideas, apps, podcasts, courses, games), people, capsules and messages (up to 2), one picture per item, search, reminders, sharing, home-screen widgets, light and dark themes, backup.')

k('fieldCoursePlatform', 'پلتفرم یا سایت', 'Platform or site')
k('fieldLinkStore', 'لینک (فروشگاه یا سایت)', 'Link (store or website)')
k('fieldPositionHint', 'تا کجا رسیدم (مثلاً ۱۸:۳۲)', 'Where I stopped (e.g. 18:32)')
k('fieldDurationHint2', 'مثلاً ۴۵ یا ۱:۲۰:۰۰', 'e.g. 45 or 1:20:00')
k('typeDetails', 'مشخصات', 'Details')
k('widgetRead', 'خواندنی', 'Read')

k('widgetOfferTitle', 'ویجت «بعداً» روی صفحه‌ی اصلی؟', 'Put the Later widget on your home screen?')
k('widgetOfferBody', 'یه ویجت کوچیک و قشنگ که کارهای امروزت رو نشونت می‌ده و با یه لمس چیزی رو ذخیره می‌کنه. هر وقت خواستی می‌تونی برش داری.', 'A small, pretty widget that shows what is set for today and saves something in one tap. You can remove it any time.')
k('widgetOfferYes', 'آره، اضافه کن', 'Yes, add it')
k('widgetOfferNo', 'نه، ممنون', 'No, thanks')
k('widgetAddedToast', 'درخواست اضافه‌شدن ویجت فرستاده شد؛ تأییدش کن.', 'Widget request sent; confirm it.')
k('widgetManualHint', 'لانچر گوشی اضافه‌کردن خودکار رو پشتیبانی نمی‌کنه. روی صفحه‌ی اصلی نگه دار و «ویجت‌ها» رو بزن، بعد «بعداً» رو انتخاب کن.', 'Your launcher cannot add it automatically. Long-press the home screen, tap Widgets and pick Later.')
k('settingsWidget', 'ویجت صفحه‌ی اصلی', 'Home-screen widget')
k('settingsWidgetSub', 'کارهای امروز رو روی صفحه‌ی اصلی ببین.', 'See today\'s items on your home screen.')
k('widgetTodayEmpty', 'امروز چیزی نداری 🌿', 'Nothing for today 🌿')
k('widgetMore', '+{n} مورد دیگه', '+{n} more')
k('widgetOverdue', 'عقب‌افتاده', 'Overdue')
k('proAlreadyOwned', 'این پلن را قبلاً خریده‌ای و هنوز فعاله. یه پلن دیگه بخر یا بعد از تموم‌شدنش دوباره بخر.', 'You already own this plan and it is still active. Pick another plan, or buy it again once it ends.')
# consistency: every placeholder set must match between languages
for key, (fa, en, _) in T.items():
    if key.startswith('_select_'):
        continue
    a = set(re.findall(r'\{(\w+)\}', fa)); b = set(re.findall(r'\{(\w+)\}', en))
    assert a == b, (key, a, b)

root = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'lib', 'l10n')
for i, code in enumerate(['fa', 'en']):
    with open(os.path.join(root, f'app_{code}.arb'), 'w', encoding='utf-8') as f:
        json.dump(build(i), f, ensure_ascii=False, indent=2)
        f.write('\n')
print(len(T), 'keys')
