#!/usr/bin/env python3
"""Generates lib/l10n/app_fa.arb and app_en.arb from one table so both languages
always have identical keys. Run: python3 tool/gen_arb.py
Placeholders written as {name} are typed as String (pre-format numbers/dates
in Dart). Keys starting with '_select_' are hand-written ICU."""
import json, re, os

T = {}
def k(key, fa, en, desc=None):
    T[key] = (fa, en, desc)

# ---------------------------------------------------------------- general
k('appName', 'بعداً', 'Later')
k('tagline', 'الان لازم نیست؛ فقط فراموشش نکن.', "Not now — just don't forget it.")
k('ok', 'باشه', 'OK')
k('cancel', 'انصراف', 'Cancel')
k('save', 'ذخیره', 'Save')
k('delete', 'حذف', 'Delete')
k('edit', 'ویرایش', 'Edit')
k('close', 'بستن', 'Close')
k('retry', 'تلاش دوباره', 'Try again')
k('done', 'انجام شد', 'Done')
k('next', 'بعدی', 'Next')
k('skip', 'رد کردن', 'Skip')
k('continueLabel', 'ادامه', 'Continue')
k('undo', 'برگردان', 'Undo')
k('add', 'اضافه کن', 'Add')
k('search', 'جستجو', 'Search')
k('all', 'همه', 'All')
k('none', 'هیچ‌کدام', 'None')
k('proBadge', 'Pro', 'Pro')
k('loading', 'در حال بارگذاری…', 'Loading…')
k('errorGeneric', 'یه مشکلی پیش اومد. دوباره تلاش کن.', 'Something went wrong. Please try again.')
k('errorLoad', 'بارگذاری اطلاعات ناموفق بود.', "Couldn't load your data.")
k('navHome', 'خانه', 'Home')
k('navList', 'بعداً', 'Later')
k('navHistory', 'تاریخچه', 'History')
k('navSettings', 'تنظیمات', 'Settings')
k('semAdd', 'افزودن مورد جدید', 'Add a new item')

# ------------------------------------------------------------- onboarding
k('onb1Title', 'الان لازم نیست.', "You don't need it now.")
k('onb1Body', 'ذهنت را از هزارتا کار نیمه‌کاره خالی کن.', 'Free your mind from a thousand half-finished things.')
k('onb2Title', 'هر چیزی را که نمی‌خواهی فراموش کنی، اینجا نگه دار.', "Keep anything you don't want to forget, right here.")
k('onb2Body', 'مقاله، فیلم، خرید، ایده، لینک، یه تماس… فقط بنویس یا از هر برنامه‌ای «اشتراک‌گذاری» کن.', 'An article, a movie, a purchase, an idea, a link, a call… just type it or Share it from any app.')
k('onb3Title', 'بعداً خودش به تو یادآوری می‌کند.', 'Later reminds you by itself.')
k('onb3Body', 'یه تاریخ و ساعت بده؛ یا نده و هر وقت وقت آزاد داشتی بگو «یه مورد بهم بده».', 'Give it a date and time — or don\'t, and ask "give me one" whenever you have a moment.')
k('onb4Title', 'بدون حساب کاربری، بدون سرور.', 'No account, no server.')
k('onb4Body', 'اطلاعاتت فقط روی دستگاه خودت می‌ماند و حتی بدون اینترنت کار می‌کند.', 'Your data stays on your own device and works even without internet.')
k('onb5Title', 'آماده‌ای؟', 'Ready?')
k('onb5Body', 'هر چیزی که الان وقتش نیست را همین‌جا بگذار.', "Put anything that isn't for now right here.")
k('onbStart', 'بزن بریم', "Let's go")

# --------------------------------------------------------------- legal
k('legalTitle', 'قبل از شروع', 'Before you start')
k('legalIntro', 'لطفاً قوانین استفاده و سیاست حریم خصوصی را بخوان و تأیید کن.', 'Please read and accept the Terms of Use and the Privacy Policy.')
k('termsTitle', 'قوانین استفاده', 'Terms of Use')
k('privacyTitle', 'سیاست حریم خصوصی', 'Privacy Policy')
k('legalAccept', 'قوانین استفاده و سیاست حریم خصوصی را خوانده‌ام و می‌پذیرم.', 'I have read and accept the Terms of Use and Privacy Policy.')
k('legalContinue', 'تأیید و ورود', 'Accept and continue')
k('legalLoadError', 'بارگذاری متن ناموفق بود.', "Couldn't load the text.")
k('legalUpdatedTitle', 'به‌روزرسانی قوانین', 'Updated terms')

# ------------------------------------------------------------------ home
k('homeWaiting', '{count} مورد منتظر توست', '{count} items are waiting for you')
k('homeWaitingOne', 'یک مورد منتظر توست', 'One item is waiting for you')
k('homeEmptyTitle', 'هنوز چیزی برای بعداً نداری.', 'Nothing for later yet.')
k('homeEmptyBody', 'چه خوب. فعلاً ذهنت آزاده. 🌱', 'Nice. Your mind is free for now. 🌱')
k('homeEmptyCta', 'اولین مورد را اضافه کن', 'Add your first item')
k('statToday', 'امروز', 'Today')
k('statWeek', 'این هفته', 'This week')
k('statNoDate', 'بدون تاریخ', 'No date')
k('statOverdue', 'عقب‌افتاده', 'Overdue')
k('statStale', 'مانده‌ها', 'Waiting long')
k('pickCardTitle', '🎯 یه مورد بهم بده', '🎯 Give me one')
k('pickCardSub', 'نمی‌دونی الان چی کار کنی؟ من انتخاب می‌کنم.', "Don't know what to do now? I'll choose.")
k('timeCardTitle', 'الان چقدر وقت داری؟', 'How much time do you have?')
k('minutesN', '{n} دقیقه', '{n} min')
k('hourOne', '۱ ساعت', '1 hour')
k('anyTime', 'مهم نیست', "Doesn't matter")
k('homeTodaySection', 'امروز و عقب‌افتاده‌ها', 'Today & overdue')
k('homeSeeAll', 'همه', 'See all')
k('staleBannerTitle', '{count} مورد مدت‌هاست منتظرند', '{count} items have been waiting a long time')
k('staleBannerBody', 'یه نگاه سریع بنداز؛ نگه دار یا رها کن.', 'Take a quick look: keep or let go.')

# ------------------------------------------------------ decide / smart pick
k('decideTitle', 'تصمیم نگیر', "Don't decide")
k('decideIntro', 'نمی‌دونم الان چی کار کنم.', "I don't know what to do right now.")
k('decideLabel', '🎯 پیشنهاد بعدی تو:', '🎯 Your next suggestion:')
k('decideAbout', 'حدود {n} دقیقه', 'About {n} min')
k('decideDo', 'انجامش می‌دم', "I'll do it")
k('decideLater', 'بعداً', 'Later')
k('decideAnother', 'مورد دیگری بده', 'Give me another')
k('decideNone', 'چیزی برای پیشنهاد ندارم', 'Nothing to suggest')
k('decideNoneBody', 'لیستت خالیه یا چیزی به این زمان نمی‌خوره. 🌱', 'Your list is empty or nothing fits. 🌱')
k('decideNoMore', 'مورد دیگری نمانده.', 'No more items to suggest.')
k('decideDoneToast', 'آفرین! انجام شد ✓', 'Nice! Done ✓')
k('smartPickTitle', 'پیشنهاد هوشمند', 'Smart pick')
k('smartPickHeader', 'الان چقدر وقت داری؟', 'How much time do you have now?')
k('smartPickResultsFor', 'مناسب {time}', 'Fits {time}')
k('smartPickResultsAny', 'پیشنهادها', 'Suggestions')
k('smartPickEmpty', 'برای این مدت چیزی پیدا نکردم.', "I couldn't find anything for that long.")
k('smartPickProHint', 'پیشنهاد پیشرفته (اولویت و فیلتر دسته) با Pro', 'Advanced picks (priority & category filter) with Pro')
k('smartPickCategory', 'فقط از دسته‌ی…', 'Only from category…')
k('smartPickAllCategories', 'همه‌ی دسته‌ها', 'All categories')

# ------------------------------------------------------------------ list
k('listTitle', 'بعداً', 'Later')
k('searchHint', 'جستجو در بعداً…', 'Search Later…')
k('searchAdvancedHint', 'جستجوی پیشرفته (برچسب، لینک، یادداشت) با Pro', 'Advanced search (tags, links, notes) with Pro')
k('filterAll', 'همه', 'All')
k('filterToday', 'امروز', 'Today')
k('filterWeek', 'این هفته', 'This week')
k('filterNoDate', 'بدون تاریخ', 'No date')
k('filterOverdue', 'عقب‌افتاده', 'Overdue')
k('filterHigh', 'اولویت بالا', 'High priority')
k('filterStale', 'مانده‌ها', 'Waiting long')
k('sortTitle', 'مرتب‌سازی', 'Sort')
k('sortNewest', 'جدیدترین', 'Newest')
k('sortOldest', 'قدیمی‌ترین', 'Oldest')
k('sortDeadline', 'نزدیک‌ترین موعد', 'Nearest deadline')
k('sortPriority', 'اولویت', 'Priority')
k('sortShortest', 'کوتاه‌ترین کار', 'Shortest task')
k('sortLongest', 'طولانی‌ترین کار', 'Longest task')
k('listEmptyFiltered', 'چیزی پیدا نشد', 'Nothing found')
k('listEmptyFilteredBody', 'فیلتر یا عبارت جستجو را عوض کن.', 'Try changing the filter or search.')
k('smartFiltersPro', 'فیلترهای هوشمند با Pro', 'Smart filters with Pro')

# ------------------------------------------------------------ item / cards
k('overdue', 'عقب‌افتاده', 'Overdue')
k('waitingDays', '{n} روز است منتظر', 'Waiting {n} days')
k('dueToday', 'امروز', 'Today')
k('dueTomorrow', 'فردا', 'Tomorrow')
k('atTime', 'ساعت {time}', 'at {time}')
k('noDate', 'بدون تاریخ', 'No date')
k('priorityHigh', 'اولویت بالا', 'High priority')
k('priorityNormal', 'عادی', 'Normal')
k('priorityLow', 'کم', 'Low')
k('priority', 'اولویت', 'Priority')
k('duration', 'زمان تخمینی', 'Estimated time')
k('minutesShort', '{n} د', '{n}m')
k('reminder', 'یادآوری', 'Reminder')
k('repeat', 'تکرار', 'Repeat')
k('repeatNone', 'یک‌بار', 'Once')
k('repeatDaily', 'هر روز', 'Every day')
k('repeatWeekly', 'هر هفته', 'Every week')
k('repeatMonthly', 'هر ماه', 'Every month')
k('snoozedTimes', '{n} بار به بعد رفته', 'Snoozed {n} times')
k('itemDone', 'انجام شد', 'Done')
k('itemSnooze', 'بعداً', 'Later')
k('itemDrop', 'بی‌خیالش شدم', 'Let it go')
k('itemOpenLink', 'باز کردن لینک', 'Open link')
k('itemLinkFailed', 'لینک باز نشد.', "Couldn't open the link.")
k('toastDone', 'انجام شد ✓', 'Done ✓')
k('toastDropped', 'کنار گذاشته شد', 'Set aside')
k('toastDeleted', 'حذف شد', 'Deleted')
k('toastSnoozed', 'منتقل شد به {when}', 'Moved to {when}')
k('toastSaved', 'ذخیره شد', 'Saved')
k('toastAdded', 'به بعداً اضافه شد', 'Added to Later')
k('toastReopened', 'به لیست برگشت', 'Back in your list')
k('confirmDeleteTitle', 'حذف این مورد؟', 'Delete this item?')
k('confirmDeleteBody', 'این مورد برای همیشه پاک می‌شود.', 'This item will be permanently deleted.')
k('createdOn', 'ثبت‌شده در {date}', 'Added on {date}')
k('itemNotFound', 'این مورد دیگر وجود ندارد.', 'This item no longer exists.')

# --------------------------------------------------------------- add / edit
k('addTitle', 'چیزی برای بعداً', 'Something for later')
k('editTitle', 'ویرایش', 'Edit')
k('titleHint', 'چی رو بذارم برای بعداً؟', 'What should I keep for later?')
k('titleRequired', 'یه عنوان بنویس', 'Write a title')
k('moreOptions', 'گزینه‌های بیشتر', 'More options')
k('lessOptions', 'کمتر', 'Fewer options')
k('fieldDescription', 'توضیح', 'Description')
k('fieldNote', 'یادداشت', 'Note')
k('fieldUrl', 'لینک', 'Link')
k('urlInvalid', 'لینک معتبر نیست (فقط http و https).', 'Invalid link (http and https only).')
k('fieldTags', 'برچسب‌ها', 'Tags')
k('fieldTagsHint', 'با کاما جدا کن', 'Separate with commas')
k('fieldCategory', 'دسته', 'Category')
k('fieldDate', 'تاریخ', 'Date')
k('fieldTime', 'ساعت', 'Time')
k('datePick', 'انتخاب تاریخ…', 'Pick a date…')
k('timePick', 'انتخاب ساعت…', 'Pick a time…')
k('timeNone', 'بدون ساعت', 'No time')
k('reminderOff', 'بدون یادآوری', 'No reminder')
k('reminderAtTime', 'سر وقت', 'At the time')
k('reminderBefore10', '۱۰ دقیقه قبل', '10 min before')
k('reminderBefore1h', '۱ ساعت قبل', '1 hour before')
k('reminderBefore1d', '۱ روز قبل', '1 day before')
k('reminderNeedsDate', 'برای یادآوری یه تاریخ لازمه.', 'A reminder needs a date.')
k('reminderAtDefault', 'ساعت {time} (پیش‌فرض)', 'at {time} (default)')
k('repeatProHint', 'یادآوری تکرارشونده با Pro', 'Repeating reminders with Pro')
k('durationUnknown', 'نامشخص', 'Unknown')
k('durationCustom', 'دلخواه', 'Custom')
k('durationCustomHint', 'چند دقیقه؟', 'How many minutes?')
k('quickToday', 'امروز', 'Today')
k('quickTomorrow', 'فردا', 'Tomorrow')
k('quickWeekend', 'آخر هفته', 'Weekend')
k('quickNextWeek', 'هفته بعد', 'Next week')
k('quickNoDate', 'بدون تاریخ', 'No date')
k('quickCustom', 'تاریخ دیگر', 'Other date')
k('discardTitle', 'تغییرات ذخیره نشود؟', 'Discard changes?')
k('discardBody', 'چیزی که نوشته‌ای ذخیره نشده.', "What you typed hasn't been saved.")
k('discard', 'دور بینداز', 'Discard')

# ----------------------------------------------------------------- snooze
k('snoozeTitle', 'به کِی موکولش کنم؟', 'Snooze until…')
k('snoozeTonight', 'امشب', 'Tonight')
k('snoozeTomorrow', 'فردا', 'Tomorrow')
k('snoozeWeekend', 'آخر هفته', 'This weekend')
k('snoozeNextWeek', 'هفته بعد', 'Next week')
k('snoozeNextMonth', 'ماه بعد', 'Next month')
k('snoozeCustom', 'تاریخ دلخواه', 'Pick a date')
k('snoozeNoDate', 'بدون تاریخ', 'No date')
k('datePickerTitle', 'انتخاب تاریخ', 'Pick a date')
k('prevMonth', 'ماه قبل', 'Previous month')
k('nextMonth', 'ماه بعد', 'Next month')
k('today', 'امروز', 'Today')
k('clear', 'پاک کردن', 'Clear')

# ------------------------------------------------------------ stale review
k('staleTitle', 'بعداً، نه هیچ‌وقت', 'Later, not never')
k('staleQuestion', 'این مورد {days} روز است منتظر توست.\nهنوز می‌خواهی نگهش داری؟', 'This has been waiting for you for {days} days.\nDo you still want to keep it?')
k('staleKeep', 'نگه دار', 'Keep')
k('staleSnooze', 'برای بعداً تنظیم کن', 'Schedule for later')
k('staleDone', 'انجام شد', 'Done')
k('staleDrop', 'بی‌خیالش شدم', 'Let it go')
k('staleProgress', '{i} از {n}', '{i} of {n}')
k('staleAllDone', 'همه‌چی مرتبه ✨', 'All clear ✨')
k('staleAllDoneBody', 'لیستت سبک‌تر شد.', 'Your list just got lighter.')
k('staleNoPressure', 'بدون عجله؛ هیچ تصمیمی اشتباه نیست.', 'No rush; no decision is wrong.')

# ------------------------------------------------------- history / stats
k('historyTitle', 'تاریخچه', 'History')
k('periodToday', 'امروز', 'Today')
k('periodWeek', 'این هفته', 'This week')
k('periodMonth', 'این ماه', 'This month')
k('periodAll', 'همه', 'All')
k('historyEmpty', 'هنوز چیزی در تاریخچه نیست', 'Nothing in your history yet')
k('historyEmptyBody', 'کارهای انجام‌شده و کنار گذاشته‌شده اینجا می‌مانند.', 'Completed and set-aside items stay here.')
k('historyDoneAt', 'انجام شد · {date}', 'Done · {date}')
k('historyDroppedAt', 'کنار گذاشته شد · {date}', 'Set aside · {date}')
k('historyRestore', 'برگردان به لیست', 'Move back to list')
k('historyProNote', 'تاریخچه‌ی کامل (ماه و همه) با Pro', 'Full history (month & all) with Pro')
k('historyDisabled', 'ثبت تاریخچه خاموش است؛ فقط آمار ناشناس نگه داشته می‌شود.', 'History is off; only anonymous statistics are kept.')
k('statsTitle', 'آمار', 'Statistics')
k('statsDone', 'انجام‌شده', 'Completed')
k('statsDropped', 'کنار گذاشته‌شده', 'Set aside')
k('statsDeleted', 'حذف‌شده', 'Deleted')
k('statsSnoozed', 'بار به تعویق افتاده', 'Times snoozed')
k('statsActive', 'فعال', 'Active')
k('statsAvgWait', 'میانگین ماندن تا انجام', 'Average wait until done')
k('statsDaysValue', '{n} روز', '{n} days')
k('statsTopCategory', 'محبوب‌ترین دسته', 'Top category')
k('statsThisWeek', 'انجام‌شده در این هفته', 'Completed this week')
k('statsProLocked', 'آمار کامل با Pro', 'Full statistics with Pro')
k('statsNoData', '—', '—')

# ---------------------------------------------------------------- settings
k('settingsTitle', 'تنظیمات', 'Settings')
k('secAppearance', 'ظاهر', 'Appearance')
k('theme', 'تم', 'Theme')
k('themeLight', 'روشن', 'Light')
k('themeDark', 'تیره', 'Dark')
k('themeSystem', 'پیش‌فرض سیستم', 'System default')
k('accent', 'رنگ اصلی', 'Accent colour')
k('accentIndigo', 'بنفش', 'Indigo')
k('accentTeal', 'فیروزه‌ای', 'Teal')
k('accentRose', 'رُز', 'Rose')
k('accentAmber', 'کهربایی', 'Amber')
k('accentSlate', 'خاکستری', 'Slate')
k('appIcon', 'آیکون برنامه', 'App icon')
k('iconClassic', 'کلاسیک', 'Classic')
k('iconTeal', 'فیروزه‌ای', 'Teal')
k('iconRose', 'رُز', 'Rose')
k('iconDark', 'تیره', 'Dark')
k('iconChangeNote', 'با تغییر آیکون ممکن است چند لحظه‌ی دیگر در لانچر عوض شود.', 'The launcher may take a moment to refresh the icon.')
k('secReminders', 'یادآوری', 'Reminders')
k('remindersToggle', 'یادآوری‌ها', 'Reminders')
k('defaultReminderTime', 'ساعت پیش‌فرض یادآوری', 'Default reminder time')
k('privateNotifications', 'پنهان کردن متن در اعلان', 'Hide text in notifications')
k('privateNotificationsSub', 'عنوان موردها روی صفحه‌ی قفل دیده نشود.', "Item titles won't show on the lock screen.")
k('notifPermission', 'دسترسی اعلان', 'Notification access')
k('notifPermissionOn', 'فعال است', 'Enabled')
k('notifPermissionOff', 'غیرفعال است؛ برای باز کردن تنظیمات بزن', 'Disabled — tap to open settings')
k('exactAlarm', 'دقت یادآوری', 'Reminder accuracy')
k('exactAlarmOk', 'دقیق', 'Exact')
k('exactAlarmOff', 'تقریبی؛ «هشدار دقیق» مجاز نشده', 'Approximate — "exact alarms" not allowed')
k('batteryOptimization', 'محدودیت باتری', 'Battery restrictions')
k('batteryOptimizationSub', 'بعضی گوشی‌ها یادآوری را می‌بندند؛ بزن تا تنظیمات باز شود.', 'Some phones block reminders; tap to open the settings.')
k('sendTestNotification', 'ارسال اعلان آزمایشی', 'Send a test notification')
k('testNotificationSent', 'اعلان آزمایشی ارسال شد.', 'Test notification sent.')
k('secGeneral', 'عمومی', 'General')
k('language', 'زبان', 'Language')
k('langFa', 'فارسی', 'فارسی (Persian)')
k('langEn', 'English', 'English')
k('calendar', 'تقویم', 'Calendar')
k('calJalali', 'شمسی', 'Jalali (Persian)')
k('calGregorian', 'میلادی', 'Gregorian')
k('weekStart', 'شروع هفته', 'Start of week')
k('weekendDay', 'روز آخر هفته', 'Weekend day')
k('keepHistory', 'نگه داشتن تاریخچه', 'Keep history')
k('keepHistorySub', 'موردهای انجام‌شده و کنار گذاشته‌شده در آرشیو بمانند.', 'Keep completed and set-aside items in the archive.')
k('staleAfter', 'مرور مانده‌ها بعد از', 'Review long-waiting items after')
k('daysN', '{n} روز', '{n} days')
k('secData', 'اطلاعات', 'Data')
k('backupRestore', 'پشتیبان‌گیری و بازیابی', 'Backup & restore')
k('categoriesManage', 'مدیریت دسته‌ها', 'Manage categories')
k('secAbout', 'درباره', 'About')
k('proSettingsTitle', 'بعداً Pro', 'Later Pro')
k('proSettingsFree', 'نسخه‌ی رایگان', 'Free plan')
k('proSettingsActive', 'فعال تا {date}', 'Active until {date}')
k('about', 'درباره‌ی برنامه', 'About')
k('aboutBody', 'بعداً یک برنامه‌ی کوچک و سریع برای نگه‌داشتن چیزهایی است که الان وقتشان نیست؛ بدون حساب کاربری و بدون سرور.', "Later is a small, fast app for keeping things that aren't for now — no account, no server.")
k('aboutOffline', 'همه‌ی اطلاعات فقط روی دستگاه تو ذخیره می‌شود.', 'All your data is stored only on your device.')
k('aboutLicenses', 'مجوزهای متن‌باز', 'Open-source licences')
k('aboutContact', 'پشتیبانی', 'Support')
k('version', 'نسخه', 'Version')
k('versionValue', 'نسخه {v}', 'Version {v}')
k('resetApp', 'پاک کردن همه‌ی اطلاعات', 'Reset app')
k('resetAppSub', 'همه‌ی موردها، دسته‌ها، تاریخچه و تنظیمات', 'All items, categories, history and settings')
k('resetConfirmTitle', 'همه‌چیز پاک شود؟', 'Erase everything?')
k('resetConfirmBody', 'همه‌ی موردها، دسته‌ها، تاریخچه و تنظیمات این برنامه برای همیشه پاک می‌شود. این کار قابل بازگشت نیست.\n(اشتراک Pro از بین نمی‌رود.)\nپیشنهاد می‌کنیم اول پشتیبان بگیری.', 'All items, categories, history and settings will be permanently deleted. This cannot be undone.\n(Your Pro subscription is not affected.)\nWe suggest making a backup first.')
k('resetTypeHint', 'برای تأیید، کلمه‌ی «{word}» را بنویس', 'To confirm, type "{word}"')
k('resetWord', 'پاک', 'ERASE')
k('resetAction', 'پاک کردن همه‌چیز', 'Erase everything')
k('resetDone', 'همه‌چیز پاک شد.', 'Everything was erased.')

# ------------------------------------------------------------- categories
k('_select_categoryName', '{id, select, work{کار} read{خواندنی} watch{دیدنی} buy{خرید} idea{ایده} link{لینک} people{افراد} other{سایر}}', '{id, select, work{Work} read{To read} watch{To watch} buy{To buy} idea{Ideas} link{Links} people{People} other{Other}}')
k('categoryNew', 'دسته‌ی جدید', 'New category')
k('categoryEdit', 'ویرایش دسته', 'Edit category')
k('categoryNameHint', 'نام دسته', 'Category name')
k('categoryEmojiHint', 'ایموجی', 'Emoji')
k('categoryLimit', 'در نسخه‌ی رایگان تا {free} دسته‌ی سفارشی می‌توانی بسازی؛ Pro تا {pro} دسته.', 'The free plan allows {free} custom categories; Pro allows up to {pro}.')
k('categoryDeleteTitle', 'این دسته حذف شود؟', 'Delete this category?')
k('categoryDeleteBody', 'موردهای این دسته به «سایر» منتقل می‌شوند.', 'Its items will move to "Other".')
k('categoryBuiltin', 'دسته‌ی پیش‌فرض', 'Built-in category')

# ------------------------------------------------------- backup / restore
k('backupTitle', 'پشتیبان‌گیری و بازیابی', 'Backup & restore')
k('backupIntro', 'اطلاعات فقط روی همین دستگاه است. برای جابه‌جایی یا نصب مجدد، از آن‌ها فایل پشتیبان بگیر.', 'Your data lives only on this device. Make a backup file before moving or reinstalling.')
k('backupExport', 'خروجی گرفتن از اطلاعات', 'Export my data')
k('backupExportSub', 'یک فایل ‎.later‎ با همه‌ی موردها، دسته‌ها، تاریخچه و تنظیمات', 'A .later file with all items, categories, history and settings')
k('backupImport', 'بازیابی از فایل', 'Restore from file')
k('backupImportSub', 'فایل پشتیبانِ قبلی را انتخاب کن', 'Choose a previous backup file')
k('backupLast', 'آخرین پشتیبان: {date}', 'Last backup: {date}')
k('backupNever', 'هنوز پشتیبان نگرفته‌ای', "You haven't made a backup yet")
k('backupExported', 'پشتیبان ذخیره شد ✓', 'Backup saved ✓')
k('backupAuto', 'پشتیبان خودکار هفتگی', 'Automatic weekly backup')
k('backupAutoSub', 'تا ۵ نسخه در حافظه‌ی خصوصی برنامه نگه داشته می‌شود (Pro).', 'Keeps up to 5 copies in private app storage (Pro).')
k('backupAdvancedExport', 'خروجی‌های بیشتر (Pro)', 'More export formats (Pro)')
k('exportCsv', 'خروجی CSV', 'Export CSV')
k('exportText', 'خروجی متنی (Markdown)', 'Export text (Markdown)')
k('exportSaved', 'فایل ذخیره شد ✓', 'File saved ✓')
k('restoreConfirmTitle', 'بازیابی اطلاعات؟', 'Restore data?')
k('restoreConfirmReplace', 'اطلاعات فعلی ({current} مورد) با محتوای فایل ({incoming} مورد، ساخته‌شده در {date}) جایگزین می‌شود.\nپیش از آن یک نسخه‌ی ایمنی از اطلاعات فعلی نگه داشته می‌شود.', 'Your current data ({current} items) will be replaced by the file ({incoming} items, created {date}).\nA safety copy of the current data is kept first.')
k('restoreConfirmEmpty', 'فایل شامل {incoming} مورد است (ساخته‌شده در {date}).', 'The file contains {incoming} items (created {date}).')
k('restoreAction', 'بازیابی', 'Restore')
k('restoreDone', 'اطلاعات بازیابی شد ✓', 'Data restored ✓')
k('restoreProRestored', 'اشتراک Pro هم از پشتیبان بازیابی شد.', 'Your Pro subscription was restored too.')
k('backupErrEmpty', 'فایل خالی است.', 'The file is empty.')
k('backupErrTooLarge', 'فایل خیلی بزرگ است.', 'The file is too large.')
k('backupErrNotJson', 'فایل خراب یا ناقص است.', 'The file is damaged or incomplete.')
k('backupErrNotBackup', 'این فایل پشتیبان «بعداً» نیست.', 'This is not a Later backup file.')
k('backupErrMissing', 'فایل ناقص است.', 'The file is incomplete.')
k('backupErrFuture', 'این پشتیبان با نسخه‌ی جدیدتری از برنامه ساخته شده. برنامه را به‌روزرسانی کن.', 'This backup was made by a newer version of the app. Please update the app.')
k('backupErrUnsupported', 'قالب این پشتیبان دیگر پشتیبانی نمی‌شود.', 'This backup format is no longer supported.')
k('backupErrChecksum', 'فایل آسیب دیده یا ویرایش شده است.', 'The file is damaged or has been modified.')
k('backupErrInvalid', 'محتوای فایل معتبر نیست.', 'The file contents are not valid.')
k('backupErrMigration', 'به‌روزرسانی قالب فایل ناموفق بود.', 'Upgrading the file format failed.')
k('backupErrGeneric', 'بازیابی انجام نشد. اطلاعات فعلی دست‌نخورده ماند.', 'Restore failed. Your current data was not changed.')
k('backupNoChange', 'اطلاعات فعلی تغییری نکرد.', 'Your current data was not changed.')

# -------------------------------------------------------------------- Pro
k('proTitle', 'بعداً Pro', 'Later Pro')
k('proHeadline', 'امکانات بیشتر برای کسانی که «بعداً» را زیاد استفاده می‌کنند.', 'More power for people who use Later a lot.')
k('proFreeNote', 'نسخه‌ی رایگان همچنان کامل قابل استفاده است و هیچ اطلاعاتی محدود یا حذف نمی‌شود.', 'The free version stays fully usable and none of your data is ever limited or deleted.')
k('proActiveUntil', 'فعال تا {date}', 'Active until {date}')
k('proRemaining', '{n} روز باقی مانده', '{n} days left')
k('proExpiredNote', 'اشتراک Pro تمام شده؛ اطلاعاتت سالم است و فقط امکانات Pro غیرفعال شده‌اند.', 'Your Pro has ended. Your data is safe; only Pro features are switched off.')
k('proPlan1', '۱ ماهه', '1 month')
k('proPlan3', '۳ ماهه', '3 months')
k('proPlan6', '۶ ماهه', '6 months')
k('proPlanDay1', '۱ روزه (آزمایشی)', '1 day (test)')
k('proPlanDay7', '۷ روزه (آزمایشی)', '7 days (test)')
k('priceToman', '{price} تومان', '{price} Toman')
k('proBuy', 'خرید', 'Buy')
k('proExtend', 'تمدید', 'Extend')
k('proStackNote', 'با خرید جدید، روزهای باقی‌مانده حفظ می‌شود و مدت تازه به آن اضافه می‌شود.', 'A new purchase keeps your remaining days and adds the new period on top.')
k('proRestore', 'بازیابی خریدها', 'Restore purchases')
k('proRestored', '{n} خرید بازیابی شد', '{n} purchase(s) restored')
k('proNothingToRestore', 'خرید بازیابی‌نشده‌ای پیدا نشد.', 'No unrestored purchases found.')
k('proPurchaseSuccess', 'Pro فعال شد 🎉', 'Pro activated 🎉')
k('proPurchaseCancelled', 'خرید لغو شد.', 'Purchase cancelled.')
k('proPurchaseUnavailable', 'سرویس پرداخت در دسترس نیست. برنامه‌ی کافه‌بازار را بررسی کن.', 'Billing is unavailable. Check the Cafe Bazaar app.')
k('proPurchaseFailed', 'خرید انجام نشد. دوباره تلاش کن.', 'The purchase failed. Please try again.')
k('proTamper', 'اطلاعات اشتراک معتبر نبود و بازنشانی شد. اگر خرید کرده‌ای، «بازیابی خریدها» را بزن.', 'Subscription data was invalid and was reset. If you purchased, tap "Restore purchases".')
k('proF1', 'پیشنهاد هوشمند پیشرفته', 'Advanced smart pick')
k('proF2', 'فیلترها و جستجوی پیشرفته', 'Smart filters & advanced search')
k('proF3', 'آمار و تاریخچه‌ی کامل', 'Full statistics & history')
k('proF4', 'دسته‌های سفارشی بیشتر', 'More custom categories')
k('proF5', 'یادآوری تکرارشونده و پیشرفته', 'Recurring & advanced reminders')
k('proF6', 'ویجت‌های پیشرفته', 'Advanced widgets')
k('proF7', 'تم‌ها و آیکون‌های بیشتر', 'More themes & icons')
k('proF8', 'پشتیبان خودکار و خروجی‌های بیشتر', 'Auto backups & more exports')
k('proLockedTitle', 'این امکان مخصوص Pro است', 'This is a Pro feature')
k('proLockedBody', 'با Pro این و چند امکان دیگر باز می‌شود. نسخه‌ی رایگان همچنان کامل است.', 'Pro unlocks this and more. The free version remains complete.')
k('proSeePlans', 'دیدن پلن‌ها', 'See plans')
k('notNow', 'حالا نه', 'Not now')

# ------------------------------------------------------------- QA tools
k('qaTitle', 'ابزار تست (فقط نسخه‌ی آزمایشی)', 'Test tools (test build only)')
k('qaNote', 'این بخش در نسخه‌ی بازار وجود ندارد.', 'This section does not exist in the store build.')
k('qaGrantPlan', 'شبیه‌سازی خرید {plan}', 'Simulate buying {plan}')
k('qaClearPro', 'حذف Pro', 'Remove Pro')
k('qaAdvance', 'جلو بردن ساعت برنامه: {n} روز', 'Advance app clock: {n} days')
k('qaResetTime', 'بازنشانی ساعت شبیه‌سازی‌شده', 'Reset simulated clock')
k('qaClock', 'ساعت برنامه: {date}', 'App clock: {date}')
k('qaSeed', 'افزودن {n} مورد نمونه', 'Add {n} sample items')
k('qaSeeded', '{n} مورد اضافه شد.', '{n} items added.')
k('qaNotifNow', 'اعلان همین حالا', 'Notification now')
k('qaNotifIn', 'اعلان تا {s} ثانیه‌ی دیگر', 'Notification in {s} seconds')
k('qaProState', 'وضعیت Pro: {state}', 'Pro state: {state}')

# ---------------------------------------------------- notifications & misc
k('notifChannelName', 'یادآوری‌ها', 'Reminders')
k('notifChannelDescription', 'یادآوری موردهایی که برای بعداً گذاشته‌ای', 'Reminders for the items you kept for later')
k('notifActionDone', 'انجام شد', 'Done')
k('notifActionTomorrow', 'فردا', 'Tomorrow')
k('notifPrivateBody', 'یه مورد منتظر توست', 'An item is waiting for you')
k('notifBodyGeneric', 'بعداً', 'Later')
k('notifTestTitle', 'اعلان آزمایشی', 'Test notification')
k('notifTestBody', 'اگر این را می‌بینی، اعلان‌ها کار می‌کنند ✓', "If you can see this, notifications work ✓")
k('reminderPermissionBanner', 'اجازه‌ی اعلان داده نشده؛ یادآوری‌ها نمایش داده نمی‌شوند.', "Notification permission isn't granted; reminders won't show.")
k('reminderSyncFailed', 'برخی یادآوری‌ها ثبت نشدند.', "Some reminders couldn't be scheduled.")
k('reminderApproximate', 'یادآوری‌ها تقریبی‌اند؛ برای دقت بیشتر «هشدار دقیق» را مجاز کن.', 'Reminders are approximate; allow "exact alarms" for better accuracy.')
k('permissionDeniedTitle', 'اجازه‌ی اعلان لازم است', 'Notification permission needed')
k('permissionDeniedBody', 'برای اینکه بعداً بتونم یادت بندازم، اجازه‌ی اعلان را فعال کن.', 'Enable notifications so I can remind you later.')
k('openSettings', 'باز کردن تنظیمات', 'Open settings')
k('shareAdded', '«{title}» به بعداً اضافه شد', '"{title}" added to Later')
k('widgetWaiting', '{n} مورد منتظرند', '{n} waiting')
k('widgetEmpty', 'چیزی منتظر نیست 🌱', 'Nothing waiting 🌱')
k('widgetAdd', '+ اضافه کن', '+ Add')
k('widgetPick', '🎯 پیشنهاد', '🎯 Pick')
k('widgetProOnly', 'ویجت پیشرفته مخصوص Pro است', 'The advanced widget is a Pro feature')
k('widgetSuggestion', 'پیشنهاد', 'Suggestion')
k('shortcutAdd', 'اضافه کردن', 'Add')
k('shortcutPick', 'یه مورد بهم بده', 'Give me one')
k('shortcutSearch', 'جستجو', 'Search')
k('licensesLegalese', 'ساخته‌شده با فلاتر. فونت وزیرمتن (مجوز OFL).', 'Built with Flutter. Vazirmatn font (OFL).')


def build(lang_idx):
    out = {'@@locale': ['fa', 'en'][lang_idx]}
    for key, (fa, en, desc) in T.items():
        text = (fa, en)[lang_idx]
        if key.startswith('_select_'):
            name = key[len('_select_'):]
            out[name] = text
            if lang_idx == 0:
                out['@' + name] = {'placeholders': {'id': {'type': 'String'}}}
            continue
        out[key] = text
        if lang_idx == 0:
            # placeholders come from the Persian (template) text
            names = sorted(set(re.findall(r'\{(\w+)\}', fa)))
            meta = {}
            if names:
                meta['placeholders'] = {n: {'type': 'String'} for n in names}
            if desc:
                meta['description'] = desc
            if meta:
                out['@' + key] = meta
    return out

# consistency: every placeholder set must match between languages
for key, (fa, en, _) in T.items():
    if key.startswith('_select_'):
        continue
    a = set(re.findall(r'\{(\w+)\}', fa)); b = set(re.findall(r'\{(\w+)\}', en))
    assert a == b, (key, a, b)

root = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'lib', 'l10n')
for i, code in enumerate(['fa', 'en']):
    with open(os.path.join(root, f'app_{code}.arb'), 'w', encoding='utf-8') as f:
        json.dump(build(i), f, ensure_ascii=False, indent=2)
        f.write('\n')
print(len(T), 'keys')
